// GENERATED by @edgedb/generate v0.4.1

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _app_cm from "./app_cm";
import type * as _sys_core from "./sys_core";
import type * as _std from "./std";
export type $MoedParticipantλShape = $.typeutil.flatten<_app_cm.$CmClientλShape & {
  "office": $.LinkDesc<_sys_core.$SysObj, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "consentDisclaimer": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "ssn": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $MoedParticipant = $.ObjectType<"org_moed::MoedParticipant", $MoedParticipantλShape, null, [
  ..._app_cm.$CmClient['__exclusives__'],
]>;
const $MoedParticipant = $.makeType<$MoedParticipant>(_.spec, "d75af72d-92b5-11ef-901c-5315ce8c1da7", _.syntax.literal);

const MoedParticipant: $.$expr_PathNode<$.TypeSet<$MoedParticipant, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($MoedParticipant, $.Cardinality.Many), null);



export { $MoedParticipant, MoedParticipant };

type __defaultExports = {
  "MoedParticipant": typeof MoedParticipant
};
const __defaultExports: __defaultExports = {
  "MoedParticipant": MoedParticipant
};
export default __defaultExports;
