// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _sys_core from "./sys_core";
export type $CrmClientλShape = $.typeutil.flatten<_sys_core.$SysObjEntλShape & {
}>;
type $CrmClient = $.ObjectType<"app_crm::CrmClient", $CrmClientλShape, null, [
  ..._sys_core.$SysObjEnt['__exclusives__'],
], "app_crm::CrmClient">;
const $CrmClient = $.makeType<$CrmClient>(_.spec, "aaeb566c-d19f-11ef-b643-a97a7d2c9935", _.syntax.literal);

const CrmClient: $.$expr_PathNode<$.TypeSet<$CrmClient, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($CrmClient, $.Cardinality.Many), null);



export { $CrmClient, CrmClient };

type __defaultExports = {
  "CrmClient": typeof CrmClient
};
const __defaultExports: __defaultExports = {
  "CrmClient": CrmClient
};
export default __defaultExports;
