// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _sys_core from "./sys_core";
import type * as _std from "./std";
import type * as _sys_user from "./sys_user";
import type * as _sys_db from "./sys_db";
import type * as _default from "./default";
export type $SysMigrλShape = $.typeutil.flatten<_sys_core.$SysObjλShape & {
  "tablesSource": $.LinkDesc<$SysMigrSourceTable, $.Cardinality.Many, {}, false, false,  false, false>;
  "tablesTarget": $.LinkDesc<$SysMigrTargetTable, $.Cardinality.Many, {}, false, false,  false, false>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $SysMigr = $.ObjectType<"sys_migr::SysMigr", $SysMigrλShape, null, [
  ..._sys_core.$SysObj['__exclusives__'],
], "sys_migr::SysMigr">;
const $SysMigr = $.makeType<$SysMigr>(_.spec, "801761ea-0ebc-11ef-a650-79ab8a1ff5be", _.syntax.literal);

const SysMigr: $.$expr_PathNode<$.TypeSet<$SysMigr, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysMigr, $.Cardinality.Many), null);

export type $SysMigrSourceColumnλShape = $.typeutil.flatten<_sys_user.$MgmtλShape & {
  "codeDataType": $.LinkDesc<_sys_core.$SysCode, $.Cardinality.One, {}, false, false,  false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<columns[is sys_migr::SysMigrSourceTable]": $.LinkDesc<$SysMigrSourceTable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<columns": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysMigrSourceColumn = $.ObjectType<"sys_migr::SysMigrSourceColumn", $SysMigrSourceColumnλShape, null, [
  ..._sys_user.$Mgmt['__exclusives__'],
], "sys_migr::SysMigrSourceColumn">;
const $SysMigrSourceColumn = $.makeType<$SysMigrSourceColumn>(_.spec, "800f196d-0ebc-11ef-b8ec-ad843f5a460d", _.syntax.literal);

const SysMigrSourceColumn: $.$expr_PathNode<$.TypeSet<$SysMigrSourceColumn, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysMigrSourceColumn, $.Cardinality.Many), null);

export type $SysMigrSourceTableλShape = $.typeutil.flatten<_sys_user.$MgmtλShape & {
  "codeMigrSourceType": $.LinkDesc<_sys_core.$SysCode, $.Cardinality.One, {}, false, false,  false, false>;
  "columns": $.LinkDesc<$SysMigrSourceColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "exprSelect": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<tablesSource[is sys_migr::SysMigr]": $.LinkDesc<$SysMigr, $.Cardinality.Many, {}, false, false,  false, false>;
  "<tablesSource": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysMigrSourceTable = $.ObjectType<"sys_migr::SysMigrSourceTable", $SysMigrSourceTableλShape, null, [
  ..._sys_user.$Mgmt['__exclusives__'],
], "sys_migr::SysMigrSourceTable">;
const $SysMigrSourceTable = $.makeType<$SysMigrSourceTable>(_.spec, "80111d77-0ebc-11ef-98f8-358c7adbb083", _.syntax.literal);

const SysMigrSourceTable: $.$expr_PathNode<$.TypeSet<$SysMigrSourceTable, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysMigrSourceTable, $.Cardinality.Many), null);

export type $SysMigrTargetColumnλShape = $.typeutil.flatten<_sys_user.$MgmtλShape & {
  "column": $.LinkDesc<_sys_db.$SysColumn, $.Cardinality.One, {}, false, false,  false, false>;
  "expr": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "isActive": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "orderDefine": $.PropertyDesc<_default.$nonNegative, $.Cardinality.One, false, false, false, false>;
  "<columns[is sys_migr::SysMigrTargetTable]": $.LinkDesc<$SysMigrTargetTable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<columns": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysMigrTargetColumn = $.ObjectType<"sys_migr::SysMigrTargetColumn", $SysMigrTargetColumnλShape, null, [
  ..._sys_user.$Mgmt['__exclusives__'],
], "sys_migr::SysMigrTargetColumn">;
const $SysMigrTargetColumn = $.makeType<$SysMigrTargetColumn>(_.spec, "80137701-0ebc-11ef-bb5b-27dfed2c5e66", _.syntax.literal);

const SysMigrTargetColumn: $.$expr_PathNode<$.TypeSet<$SysMigrTargetColumn, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysMigrTargetColumn, $.Cardinality.Many), null);

export type $SysMigrTargetTableλShape = $.typeutil.flatten<_sys_user.$MgmtλShape & {
  "table": $.LinkDesc<_sys_db.$SysTable, $.Cardinality.One, {}, false, false,  false, false>;
  "columns": $.LinkDesc<$SysMigrTargetColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "isActive": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "isInitTable": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "orderDefine": $.PropertyDesc<_default.$nonNegative, $.Cardinality.One, false, false, false, false>;
  "<tablesTarget[is sys_migr::SysMigr]": $.LinkDesc<$SysMigr, $.Cardinality.Many, {}, false, false,  false, false>;
  "<tablesTarget": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysMigrTargetTable = $.ObjectType<"sys_migr::SysMigrTargetTable", $SysMigrTargetTableλShape, null, [
  ..._sys_user.$Mgmt['__exclusives__'],
], "sys_migr::SysMigrTargetTable">;
const $SysMigrTargetTable = $.makeType<$SysMigrTargetTable>(_.spec, "80155528-0ebc-11ef-a92c-c1a24895d1aa", _.syntax.literal);

const SysMigrTargetTable: $.$expr_PathNode<$.TypeSet<$SysMigrTargetTable, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysMigrTargetTable, $.Cardinality.Many), null);



export { $SysMigr, SysMigr, $SysMigrSourceColumn, SysMigrSourceColumn, $SysMigrSourceTable, SysMigrSourceTable, $SysMigrTargetColumn, SysMigrTargetColumn, $SysMigrTargetTable, SysMigrTargetTable };

type __defaultExports = {
  "SysMigr": typeof SysMigr;
  "SysMigrSourceColumn": typeof SysMigrSourceColumn;
  "SysMigrSourceTable": typeof SysMigrSourceTable;
  "SysMigrTargetColumn": typeof SysMigrTargetColumn;
  "SysMigrTargetTable": typeof SysMigrTargetTable
};
const __defaultExports: __defaultExports = {
  "SysMigr": SysMigr,
  "SysMigrSourceColumn": SysMigrSourceColumn,
  "SysMigrSourceTable": SysMigrSourceTable,
  "SysMigrTargetColumn": SysMigrTargetColumn,
  "SysMigrTargetTable": SysMigrTargetTable
};
export default __defaultExports;
