// GENERATED by @gel/generate v0.6.4

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _sys_core from "./sys_core";
import type * as _sys_user from "./sys_user";
import type * as _std from "./std";
export type $SysApiλShape = $.typeutil.flatten<Omit<_sys_core.$SysObjAttrλShape, "codeAttrType"> & {
  "codeAttrType": $.LinkDesc<_sys_core.$SysCode, $.Cardinality.One, {}, false, false,  false, true>;
  "tables": $.LinkDesc<$SysApiTable, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysApi = $.ObjectType<"sys_api::SysApi", $SysApiλShape, null, [
  ..._sys_core.$SysObjAttr['__exclusives__'],
], "sys_api::SysApi">;
const $SysApi = $.makeType<$SysApi>(_.spec, "89340e8b-8bf5-11f0-bbd0-4318dad19fc7", _.syntax.literal);

const SysApi: $.$expr_PathNode<$.TypeSet<$SysApi, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysApi, $.Cardinality.Many), null);

export type $SysApiTableλShape = $.typeutil.flatten<_sys_user.$MgmtλShape & {
  "apiTabLocalMod": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "apiTabLocalName": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "apiTabRemoteName": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "isActive": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "file": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "<tables[is sys_api::SysApi]": $.LinkDesc<$SysApi, $.Cardinality.Many, {}, false, false,  false, false>;
  "<tables": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysApiTable = $.ObjectType<"sys_api::SysApiTable", $SysApiTableλShape, null, [
  ..._sys_user.$Mgmt['__exclusives__'],
  {apiTabRemoteName: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },apiTabLocalMod: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },apiTabLocalName: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "sys_api::SysApiTable">;
const $SysApiTable = $.makeType<$SysApiTable>(_.spec, "a12191dd-8c04-11f0-b598-f7e23eec4650", _.syntax.literal);

const SysApiTable: $.$expr_PathNode<$.TypeSet<$SysApiTable, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysApiTable, $.Cardinality.Many), null);



export { $SysApi, SysApi, $SysApiTable, SysApiTable };

type __defaultExports = {
  "SysApi": typeof SysApi;
  "SysApiTable": typeof SysApiTable
};
const __defaultExports: __defaultExports = {
  "SysApi": SysApi,
  "SysApiTable": SysApiTable
};
export default __defaultExports;
