// GENERATED by @edgedb/generate v0.4.1

import type * as edgedb from "edgedb";
export namespace std {
  export interface BaseObject {
    "id": string;
  }
  export interface $Object extends BaseObject {}
  export type Endian = "Little" | "Big";
  export interface FreeObject extends BaseObject {}
  export type JsonEmpty = "ReturnEmpty" | "ReturnTarget" | "Error" | "UseNull" | "DeleteKey";
  export namespace enc {
    export type Base64Alphabet = "standard" | "urlsafe";
  }
}
export namespace sys_user {
  export interface Mgmt extends std.$Object {
    "createdAt": Date;
    "modifiedAt"?: Date | null;
    "createdBy": UserRoot;
    "modifiedBy": UserRoot;
  }
  export interface UserRoot extends std.$Object {
    "userName": string;
    "person": SysPerson;
  }
  export interface SysUser extends UserRoot, Mgmt {
    "orgs": sys_core.SysOrg[];
    "owner": sys_core.SysOrg;
    "userTypes": SysUserType[];
    "password": string;
  }
  export interface SYS_USER extends SysUser {}
  export interface SYS_USER_ID extends SysUser {}
  export interface SysStaff extends Mgmt {
    "person": SysPerson;
    "roles": sys_core.SysCode[];
    "owner": sys_core.SysOrg;
  }
  export interface SysUserType extends sys_core.SysObj {
    "userTypeResources": SysUserTypeResource[];
    "userTypeTags": SysUserTypeTag[];
  }
  export interface SysUserTypeResource extends std.$Object {
    "codeUserTypeResource": sys_core.SysCode;
    "userTypeResource": sys_core.SysObj;
    "isAccessible": boolean;
  }
  export interface SysUserTypeTag extends std.$Object {
    "codeUserTypeTag": sys_core.SysCodeType;
    "isAccessible": boolean;
  }
  export interface SysWidget extends sys_core.SysObj {}
  export interface currentUser extends SysUser {}
}
export namespace app_cm {
  export interface CmClient extends sys_user.Mgmt {
    "owner": sys_core.SysOrg;
    "person": SysPerson;
    "agencyId"?: string | null;
    "school"?: string | null;
  }
  export interface CmClientServiceFlow extends sys_user.Mgmt {
    "client": CmClient;
    "codeReferralEndType"?: sys_core.SysCode | null;
    "codeReferralType"?: sys_core.SysCode | null;
    "serviceFlow": CmServiceFlow;
    "dateEnd"?: edgedb.LocalDate | null;
    "dateEndEst"?: edgedb.LocalDate | null;
    "dateReferral": edgedb.LocalDate;
    "dateStart"?: edgedb.LocalDate | null;
    "dateStartEst"?: edgedb.LocalDate | null;
    "note"?: string | null;
  }
  export interface CmCohort extends sys_core.SysObj {
    "codeStatus"?: sys_core.SysCode | null;
    "cohortAttds": CmCohortAttd[];
    "staffAdmin"?: sys_user.SysStaff | null;
    "staffAgency"?: sys_user.SysStaff | null;
    "staffInstructor"?: sys_user.SysStaff | null;
    "venue"?: sys_core.SysOrg | null;
    "capacity"?: number | null;
    "cost"?: number | null;
    "dateEnd"?: edgedb.LocalDate | null;
    "dateStart"?: edgedb.LocalDate | null;
    "isCohortRequired"?: string | null;
    "note"?: string | null;
    "schedule"?: string | null;
    "course"?: CmCourse | null;
  }
  export interface CmCohortAttd extends sys_user.Mgmt {
    "date": edgedb.LocalDate;
    "hours": number;
    "note"?: string | null;
    "cohortId"?: string | null;
    "file"?: unknown | null;
  }
  export interface CmCourse extends sys_core.SysObj {
    "cohorts": CmCohort[];
    "codeMultiCerts": sys_core.SysCode[];
    "codeMultiExams": sys_core.SysCode[];
    "codeMultiItemsIncluded": sys_core.SysCode[];
    "codeMultiItemsNotIncluded": sys_core.SysCode[];
    "codeMultiRqmts": sys_core.SysCode[];
    "codeSector"?: sys_core.SysCode | null;
    "codeStatus"?: sys_core.SysCode | null;
    "codeTypePayment"?: sys_core.SysCodeType | null;
    "provider"?: sys_core.SysOrg | null;
    "staffAdmin"?: sys_user.SysStaff | null;
    "staffAgency"?: sys_user.SysStaff | null;
    "description"?: string | null;
    "schedule"?: string | null;
  }
  export interface CmCsfData extends sys_user.Mgmt {
    "csf": CmClientServiceFlow;
  }
  export interface CmCsfCohort extends CmCsfData {
    "codeStatus": sys_core.SysCode;
    "dateEnd"?: edgedb.LocalDate | null;
    "dateEndEst"?: edgedb.LocalDate | null;
    "dateReferral"?: edgedb.LocalDate | null;
    "dateStart"?: edgedb.LocalDate | null;
    "dateStartEst"?: edgedb.LocalDate | null;
    "note"?: string | null;
    "cohort": CmCohort;
  }
  export interface CmCsfCohortAttd extends sys_user.Mgmt {
    "codeCmCohortAttdDuration": sys_core.SysCode;
    "cohortAttd": CmCohortAttd;
    "computedHours"?: number | null;
    "csfCohort": CmCsfCohort;
    "note"?: string | null;
  }
  export interface CmCsfDocument extends CmCsfData {
    "codeType": sys_core.SysCode;
    "staffAgency": sys_user.SysStaff;
    "dateExpires"?: edgedb.LocalDate | null;
    "dateIssued": edgedb.LocalDate;
    "isShareWithClient"?: string | null;
    "note"?: string | null;
    "file"?: unknown | null;
  }
  export interface CmCsfJobPlacement extends CmCsfData {
    "codeJobType": sys_core.SysCode;
    "codePlacementRelated": sys_core.SysCode;
    "codeWageType": sys_core.SysCode;
    "staffAgency": sys_user.SysStaff;
    "dateStart": edgedb.LocalDate;
    "dateSubmitted": edgedb.LocalDate;
    "employerContactEmail"?: string | null;
    "employerContactNameFirst"?: string | null;
    "employerContactNameLast"?: string | null;
    "employerName": string;
    "hoursPerWeek": number;
    "note"?: string | null;
    "title": string;
    "wage"?: number | null;
  }
  export interface CmCsfNote extends CmCsfData {
    "codeType": sys_core.SysCode;
    "date": edgedb.LocalDate;
    "note"?: string | null;
  }
  export interface CmCsfSchoolPlacement extends CmCsfData {
    "codeCollegeStatus": sys_core.SysCode;
    "collegeGPA"?: string | null;
    "collegeGradYear"?: number | null;
    "collegeMajor"?: string | null;
    "collegeName"?: string | null;
    "date": edgedb.LocalDate;
    "note"?: string | null;
  }
  export interface CmServiceFlow extends sys_core.SysObj {}
}
export namespace sys_core {
  export interface ObjRoot extends std.$Object {
    "header"?: string | null;
    "name": string;
  }
  export interface SysObj extends ObjRoot, sys_user.Mgmt {
    "owner": ObjRoot;
  }
  export interface SysCode extends SysObj {
    "valueDecimal"?: number | null;
    "parent"?: SysCode | null;
    "order"?: number | null;
    "valueInteger"?: number | null;
    "valueString"?: string | null;
    "codeType": SysCodeType;
  }
  export interface SysCodeType extends SysObj {
    "parent"?: SysCodeType | null;
    "order"?: number | null;
  }
  export interface SysDataObj extends SysObj {
    "actionsQuery": SysDataObjActionQuery[];
    "columns": SysDataObjColumn[];
    "parentColumn"?: sys_db.SysColumn | null;
    "parentTable"?: sys_db.SysTable | null;
    "tables": SysDataObjTable[];
    "actionFieldGroup"?: SysDataObjActionFieldGroup | null;
    "isListSuppressSelect"?: boolean | null;
    "listEditPresetExpr"?: string | null;
    "isListEdit": boolean;
    "codeListEditPresetType"?: SysCode | null;
    "codeCardinality": SysCode;
    "codeComponent": SysCode;
    "processType"?: SysCode | null;
    "description"?: string | null;
    "exprFilter"?: string | null;
    "exprObject"?: string | null;
    "parentFilterExpr"?: string | null;
    "subHeader"?: string | null;
    "exprSort"?: string | null;
    "listReorderColumn"?: sys_db.SysColumn | null;
    "isListHideSearch"?: boolean | null;
  }
  export interface SysDataObjActionField extends SysObj {
    "codePacketAction": SysCode;
    "actionFieldConfirms": SysDataObjActionFieldConfirm[];
    "actionFieldShows": SysDataObjActionFieldShow[];
    "codeActionFieldTriggerEnable": SysCode;
    "codeColor"?: SysCode | null;
    "isListRowAction": boolean;
  }
  export interface SysDataObjActionFieldConfirm extends sys_user.Mgmt {
    "codeTriggerConfirmConditional": SysCode;
    "codeConfirmType": SysCode;
    "confirmButtonLabelCancel"?: string | null;
    "confirmButtonLabelConfirm"?: string | null;
    "confirmMessage"?: string | null;
    "confirmTitle"?: string | null;
  }
  export interface SysDataObjActionFieldGroup extends SysObj {
    "actionFieldItems": SysDataObjActionFieldGroupItem[];
  }
  export interface SysDataObjActionFieldGroupItem extends sys_user.Mgmt {
    "orderDefine": number;
    "action": SysDataObjActionField;
  }
  export interface SysDataObjActionFieldShow extends sys_user.Mgmt {
    "codeTriggerShow": SysCode;
    "isRequired": boolean;
  }
  export interface SysDataObjActionQuery extends sys_user.Mgmt {
    "parms": SysDataObjActionQueryParm[];
    "triggers": SysDataObjActionQueryTrigger[];
    "name": string;
  }
  export interface SysDataObjActionQueryParm extends sys_user.Mgmt {
    "key": string;
    "value": string;
  }
  export interface SysDataObjActionQueryTrigger extends sys_user.Mgmt {
    "codeQueryType": SysCode;
    "codeTriggerTiming": SysCode;
  }
  export interface SysDataObjColumn extends sys_user.Mgmt {
    "codeAccess"?: SysCode | null;
    "codeColor"?: SysCode | null;
    "codeDbDataOp"?: SysCode | null;
    "column"?: sys_db.SysColumn | null;
    "fieldListItems"?: SysDataObjFieldListItems | null;
    "items": SysDataObjColumnItem[];
    "linkColumns": SysDataObjColumnLink[];
    "linkTable"?: sys_db.SysTable | null;
    "customColActionMethod"?: string | null;
    "customColActionType"?: string | null;
    "customColActionValue"?: string | null;
    "customColAlign"?: string | null;
    "customColLabel"?: string | null;
    "customColPrefix"?: string | null;
    "customColSize"?: string | null;
    "customColSource"?: string | null;
    "customColSourceKey"?: string | null;
    "exprCustom"?: string | null;
    "fieldListItemsParmName"?: string | null;
    "headerAlt"?: string | null;
    "height"?: number | null;
    "indexTable"?: number | null;
    "indexWith"?: number | null;
    "isDisplayBlock"?: boolean | null;
    "linkExprSave"?: string | null;
    "linkExprSelect"?: string | null;
    "nameCustom"?: string | null;
    "width"?: number | null;
    "orderDisplay"?: number | null;
    "codeFieldElement"?: SysCode | null;
    "fieldEmbedListConfig"?: SysDataObjFieldEmbedListConfig | null;
    "fieldEmbedListEdit"?: SysDataObjFieldEmbedListEdit | null;
    "fieldEmbedListSelect"?: SysDataObjFieldEmbedListSelect | null;
    "isDisplayable"?: boolean | null;
    "codeSortDir"?: SysCode | null;
    "exprPreset"?: string | null;
    "customEmbedShellFields": SysDataObjColumn[];
    "orderCrumb"?: number | null;
    "orderSort"?: number | null;
    "isExcludeInsert": boolean;
    "isExcludeSelect": boolean;
    "isExcludeUpdate": boolean;
    "orderDefine": number;
    "codeDbDataSourceValue"?: SysCode | null;
    "codeAlignmentAlt"?: SysCode | null;
    "linkExprPreset"?: string | null;
    "customColCodeColor"?: SysCode | null;
  }
  export interface SysDataObjColumnItem extends sys_user.Mgmt {
    "orderDefine": number;
    "data": string;
    "display": string;
  }
  export interface SysDataObjColumnLink extends sys_user.Mgmt {
    "column": sys_db.SysColumn;
    "orderDefine": number;
  }
  export interface SysDataObjFieldEmbedListConfig extends SysObj {
    "dataObjEmbed": SysDataObj;
    "dataObjModal": SysDataObj;
    "actionFieldGroupModal": SysDataObjActionFieldGroup;
  }
  export interface SysDataObjFieldEmbedListEdit extends SysObj {
    "dataObjEmbed": SysDataObj;
  }
  export interface SysDataObjFieldEmbedListSelect extends SysObj {
    "dataObjList": SysDataObj;
    "btnLabelComplete": string;
    "actionFieldGroupModal": SysDataObjActionFieldGroup;
  }
  export interface SysDataObjFieldListItems extends SysObj {
    "table"?: sys_db.SysTable | null;
    "codeDataTypeDisplay"?: SysCode | null;
    "codeMask"?: SysCode | null;
    "exprFilter"?: string | null;
    "exprPropDisplay"?: string | null;
    "exprWith"?: string | null;
    "exprSort"?: string | null;
  }
  export interface SysDataObjTable extends sys_user.Mgmt {
    "columnParent"?: sys_db.SysColumn | null;
    "table": sys_db.SysTable;
    "index": number;
    "indexParent"?: number | null;
  }
  export interface SysDataObjWith extends sys_user.Mgmt {
    "expr": string;
    "index": number;
  }
  export interface SysEnt extends SysObj {
    "roles": SysCode[];
  }
  export interface SysNodeObj extends SysObj {
    "orderDefine": number;
    "isHideRowManager": boolean;
    "codeIcon": SysCode;
    "codeNavType": SysCode;
    "codeNodeType": SysCode;
    "dataObj"?: SysDataObj | null;
    "parent"?: SysNodeObj | null;
    "page"?: string | null;
  }
  export interface SysOrg extends SysEnt {
    "testCodeSingle"?: SysCode | null;
    "orderDefine"?: number | null;
    "testBool"?: boolean | null;
    "testDateTime"?: edgedb.LocalDateTime | null;
    "testNumberInt"?: number | null;
    "testNumberFloat"?: number | null;
    "testDate"?: edgedb.LocalDate | null;
    "testText"?: string | null;
    "codeState"?: SysCode | null;
    "addr1"?: string | null;
    "addr2"?: string | null;
    "city"?: string | null;
    "zip"?: string | null;
    "testCodeMulti": SysCode[];
  }
  export interface SysResource extends SysEnt {}
}
export interface Movie extends std.$Object {
  "character"?: Person | null;
  "title": string;
}
export interface Person extends std.$Object {
  "name": string;
}
export interface SysError extends std.$Object {
  "user": sys_user.SysUser;
  "createdAt": Date;
  "errFile"?: string | null;
  "errFunction"?: string | null;
  "errMsg"?: string | null;
}
export interface SysPerson extends std.$Object {
  "firstName": string;
  "lastName": string;
  "codeEthnicity"?: sys_core.SysCode | null;
  "codeGender"?: sys_core.SysCode | null;
  "codeRace"?: sys_core.SysCode | null;
  "codeState"?: sys_core.SysCode | null;
  "addr1"?: string | null;
  "addr2"?: string | null;
  "birthDate"?: edgedb.LocalDate | null;
  "city"?: string | null;
  "email"?: string | null;
  "favFood"?: string | null;
  "fullName": string;
  "idMigration"?: string | null;
  "middleName"?: string | null;
  "note"?: string | null;
  "phoneAlt"?: string | null;
  "phoneMobile"?: string | null;
  "title"?: string | null;
  "zip"?: string | null;
  "avatar"?: unknown | null;
}
export interface SysPersonTest extends sys_core.SysObj {
  "codeEthnicity"?: sys_core.SysCode | null;
  "codeGender"?: sys_core.SysCode | null;
  "codeRace"?: sys_core.SysCode | null;
  "codeState"?: sys_core.SysCode | null;
  "addr1"?: string | null;
  "addr2"?: string | null;
  "avatar"?: unknown | null;
  "birthDate"?: edgedb.LocalDate | null;
  "city"?: string | null;
  "email"?: string | null;
  "favFood"?: string | null;
  "firstName": string;
  "lastName": string;
  "fullName": string;
  "middleName"?: string | null;
  "note"?: string | null;
  "phoneAlt"?: string | null;
  "phoneMobile"?: string | null;
  "title"?: string | null;
  "zip"?: string | null;
}
export namespace cfg {
  export interface ConfigObject extends std.BaseObject {}
  export interface AbstractConfig extends ConfigObject {
    "extensions": ExtensionConfig[];
    "session_idle_timeout": edgedb.Duration;
    "session_idle_transaction_timeout": edgedb.Duration;
    "query_execution_timeout": edgedb.Duration;
    "listen_port": number;
    "listen_addresses": string[];
    "auth": Auth[];
    "allow_dml_in_functions"?: boolean | null;
    "allow_bare_ddl"?: AllowBareDDL | null;
    "apply_access_policies"?: boolean | null;
    "allow_user_specified_id"?: boolean | null;
    "cors_allow_origins": string[];
    "auto_rebuild_query_cache"?: boolean | null;
    "query_cache_mode"?: QueryCacheMode | null;
    "shared_buffers"?: edgedb.ConfigMemory | null;
    "query_work_mem"?: edgedb.ConfigMemory | null;
    "maintenance_work_mem"?: edgedb.ConfigMemory | null;
    "effective_cache_size"?: edgedb.ConfigMemory | null;
    "effective_io_concurrency"?: number | null;
    "default_statistics_target"?: number | null;
    "force_database_error"?: string | null;
    "_pg_prepared_statement_cache_size": number;
  }
  export type AllowBareDDL = "AlwaysAllow" | "NeverAllow";
  export interface Auth extends ConfigObject {
    "priority": number;
    "user": string[];
    "method"?: AuthMethod | null;
    "comment"?: string | null;
  }
  export interface AuthMethod extends ConfigObject {
    "transports": ConnectionTransport[];
  }
  export interface DatabaseConfig extends AbstractConfig {}
  export interface BranchConfig extends DatabaseConfig {}
  export interface Config extends AbstractConfig {}
  export type ConnectionTransport = "TCP" | "TCP_PG" | "HTTP" | "SIMPLE_HTTP" | "HTTP_METRICS" | "HTTP_HEALTH";
  export interface ExtensionConfig extends ConfigObject {
    "cfg": AbstractConfig;
  }
  export interface InstanceConfig extends AbstractConfig {}
  export interface JWT extends AuthMethod {
    "transports": ConnectionTransport[];
  }
  export interface Password extends AuthMethod {
    "transports": ConnectionTransport[];
  }
  export type QueryCacheMode = "InMemory" | "RegInline" | "PgFunc" | "Default";
  export interface SCRAM extends AuthMethod {
    "transports": ConnectionTransport[];
  }
  export interface Trust extends AuthMethod {}
  export interface mTLS extends AuthMethod {
    "transports": ConnectionTransport[];
  }
}
export namespace fts {
  export type ElasticLanguage = "ara" | "bul" | "cat" | "ces" | "ckb" | "dan" | "deu" | "ell" | "eng" | "eus" | "fas" | "fin" | "fra" | "gle" | "glg" | "hin" | "hun" | "hye" | "ind" | "ita" | "lav" | "nld" | "nor" | "por" | "ron" | "rus" | "spa" | "swe" | "tha" | "tur" | "zho" | "edb_Brazilian" | "edb_ChineseJapaneseKorean";
  export type Language = "ara" | "hye" | "eus" | "cat" | "dan" | "nld" | "eng" | "fin" | "fra" | "deu" | "ell" | "hin" | "hun" | "ind" | "gle" | "ita" | "nor" | "por" | "ron" | "rus" | "spa" | "swe" | "tur";
  export type LuceneLanguage = "ara" | "ben" | "bul" | "cat" | "ces" | "ckb" | "dan" | "deu" | "ell" | "eng" | "est" | "eus" | "fas" | "fin" | "fra" | "gle" | "glg" | "hin" | "hun" | "hye" | "ind" | "ita" | "lav" | "lit" | "nld" | "nor" | "por" | "ron" | "rus" | "spa" | "srp" | "swe" | "tha" | "tur" | "edb_Brazilian" | "edb_ChineseJapaneseKorean" | "edb_Indian";
  export type PGLanguage = "xxx_simple" | "ara" | "hye" | "eus" | "cat" | "dan" | "nld" | "eng" | "fin" | "fra" | "deu" | "ell" | "hin" | "hun" | "ind" | "gle" | "ita" | "lit" | "npi" | "nor" | "por" | "ron" | "rus" | "srp" | "spa" | "swe" | "tam" | "tur" | "yid";
  export type Weight = "A" | "B" | "C" | "D";
}
export namespace schema {
  export type AccessKind = "Select" | "UpdateRead" | "UpdateWrite" | "Delete" | "Insert";
  export interface $Object extends std.BaseObject {
    "name": string;
    "internal": boolean;
    "builtin": boolean;
    "computed_fields"?: string[] | null;
  }
  export interface SubclassableObject extends $Object {
    "abstract"?: boolean | null;
    "is_abstract"?: boolean | null;
    "final": boolean;
    "is_final": boolean;
  }
  export interface InheritingObject extends SubclassableObject {
    "bases": InheritingObject[];
    "ancestors": InheritingObject[];
    "inherited_fields"?: string[] | null;
  }
  export interface AnnotationSubject extends $Object {
    "annotations": Annotation[];
  }
  export interface AccessPolicy extends InheritingObject, AnnotationSubject {
    "subject": ObjectType;
    "access_kinds": AccessKind[];
    "condition"?: string | null;
    "action": AccessPolicyAction;
    "expr"?: string | null;
    "errmessage"?: string | null;
  }
  export type AccessPolicyAction = "Allow" | "Deny";
  export interface Alias extends AnnotationSubject {
    "expr": string;
    "type"?: Type | null;
  }
  export interface Annotation extends InheritingObject, AnnotationSubject {
    "inheritable"?: boolean | null;
  }
  export interface Type extends SubclassableObject, AnnotationSubject {
    "expr"?: string | null;
    "from_alias"?: boolean | null;
    "is_from_alias"?: boolean | null;
  }
  export interface PrimitiveType extends Type {}
  export interface CollectionType extends PrimitiveType {}
  export interface Array extends CollectionType {
    "element_type": Type;
    "dimensions"?: number[] | null;
  }
  export interface ArrayExprAlias extends Array {}
  export interface CallableObject extends AnnotationSubject {
    "params": Parameter[];
    "return_type"?: Type | null;
    "return_typemod"?: TypeModifier | null;
  }
  export type Cardinality = "One" | "Many";
  export interface VolatilitySubject extends $Object {
    "volatility"?: Volatility | null;
  }
  export interface Cast extends AnnotationSubject, VolatilitySubject {
    "from_type"?: Type | null;
    "to_type"?: Type | null;
    "allow_implicit"?: boolean | null;
    "allow_assignment"?: boolean | null;
  }
  export interface ConsistencySubject extends InheritingObject, AnnotationSubject {
    "constraints": Constraint[];
  }
  export interface Constraint extends CallableObject, InheritingObject {
    "params": Parameter[];
    "expr"?: string | null;
    "subjectexpr"?: string | null;
    "finalexpr"?: string | null;
    "errmessage"?: string | null;
    "delegated"?: boolean | null;
    "except_expr"?: string | null;
    "subject"?: ConsistencySubject | null;
  }
  export interface Delta extends $Object {
    "parents": Delta[];
  }
  export interface Extension extends AnnotationSubject, $Object {
    "package": sys.ExtensionPackage;
  }
  export interface Function extends CallableObject, VolatilitySubject {
    "preserves_optionality"?: boolean | null;
    "body"?: string | null;
    "language": string;
    "used_globals": Global[];
  }
  export interface FutureBehavior extends $Object {}
  export interface Global extends AnnotationSubject {
    "target"?: Type | null;
    "required"?: boolean | null;
    "cardinality"?: Cardinality | null;
    "expr"?: string | null;
    "default"?: string | null;
  }
  export interface Index extends InheritingObject, AnnotationSubject {
    "expr"?: string | null;
    "except_expr"?: string | null;
    "params": Parameter[];
    "kwargs"?: {name: string, expr: string}[] | null;
  }
  export interface Pointer extends ConsistencySubject, AnnotationSubject {
    "cardinality"?: Cardinality | null;
    "required"?: boolean | null;
    "readonly"?: boolean | null;
    "default"?: string | null;
    "expr"?: string | null;
    "secret"?: boolean | null;
    "source"?: Source | null;
    "target"?: Type | null;
    "rewrites": Rewrite[];
  }
  export interface Source extends $Object {
    "indexes": Index[];
    "pointers": Pointer[];
  }
  export interface Link extends Pointer, Source {
    "target"?: ObjectType | null;
    "properties": Property[];
    "on_target_delete"?: TargetDeleteAction | null;
    "on_source_delete"?: SourceDeleteAction | null;
  }
  export interface Migration extends AnnotationSubject, $Object {
    "parents": Migration[];
    "script": string;
    "message"?: string | null;
    "generated_by"?: MigrationGeneratedBy | null;
  }
  export type MigrationGeneratedBy = "DevMode" | "DDLStatement";
  export interface Module extends AnnotationSubject, $Object {}
  export interface MultiRange extends CollectionType {
    "element_type": Type;
  }
  export interface MultiRangeExprAlias extends MultiRange {}
  export interface ObjectType extends Source, ConsistencySubject, InheritingObject, Type, AnnotationSubject {
    "union_of": ObjectType[];
    "intersection_of": ObjectType[];
    "access_policies": AccessPolicy[];
    "triggers": Trigger[];
    "compound_type": boolean;
    "is_compound_type": boolean;
    "links": Link[];
    "properties": Property[];
  }
  export interface Operator extends CallableObject, VolatilitySubject {
    "operator_kind"?: OperatorKind | null;
    "abstract"?: boolean | null;
    "is_abstract"?: boolean | null;
  }
  export type OperatorKind = "Infix" | "Postfix" | "Prefix" | "Ternary";
  export interface Parameter extends $Object {
    "type": Type;
    "typemod": TypeModifier;
    "kind": ParameterKind;
    "num": number;
    "default"?: string | null;
  }
  export type ParameterKind = "VariadicParam" | "NamedOnlyParam" | "PositionalParam";
  export interface Property extends Pointer {}
  export interface PseudoType extends InheritingObject, Type {}
  export interface Range extends CollectionType {
    "element_type": Type;
  }
  export interface RangeExprAlias extends Range {}
  export interface Rewrite extends InheritingObject, AnnotationSubject {
    "subject": Pointer;
    "kind": TriggerKind;
    "expr": string;
  }
  export type RewriteKind = "Update" | "Insert";
  export interface ScalarType extends PrimitiveType, ConsistencySubject, AnnotationSubject {
    "default"?: string | null;
    "enum_values"?: string[] | null;
    "arg_values"?: string[] | null;
  }
  export type SourceDeleteAction = "DeleteTarget" | "Allow" | "DeleteTargetIfOrphan";
  export type TargetDeleteAction = "Restrict" | "DeleteSource" | "Allow" | "DeferredRestrict";
  export interface Trigger extends InheritingObject, AnnotationSubject {
    "subject": ObjectType;
    "timing": TriggerTiming;
    "kinds": TriggerKind[];
    "scope": TriggerScope;
    "expr"?: string | null;
    "condition"?: string | null;
  }
  export type TriggerKind = "Update" | "Delete" | "Insert";
  export type TriggerScope = "All" | "Each";
  export type TriggerTiming = "After" | "AfterCommitOf";
  export interface Tuple extends CollectionType {
    "named": boolean;
    "element_types": TupleElement[];
  }
  export interface TupleElement extends std.BaseObject {
    "type": Type;
    "name"?: string | null;
  }
  export interface TupleExprAlias extends Tuple {}
  export type TypeModifier = "SetOfType" | "OptionalType" | "SingletonType";
  export type Volatility = "Immutable" | "Stable" | "Volatile";
}
export namespace sys {
  export interface SystemObject extends schema.$Object {}
  export interface ExternalObject extends SystemObject {}
  export interface Database extends ExternalObject, schema.AnnotationSubject {
    "name": string;
  }
  export interface ExtensionPackage extends SystemObject, schema.AnnotationSubject {
    "script": string;
    "version": {major: number, minor: number, stage: VersionStage, stage_no: number, local: string[]};
  }
  export interface Role extends SystemObject, schema.InheritingObject, schema.AnnotationSubject {
    "name": string;
    "superuser": boolean;
    "is_superuser": boolean;
    "password"?: string | null;
    "member_of": Role[];
  }
  export type TransactionIsolation = "RepeatableRead" | "Serializable";
  export type VersionStage = "dev" | "alpha" | "beta" | "rc" | "final";
}
export namespace sys_db {
  export interface SysColumn extends sys_core.SysObj {
    "codeAlignment": sys_core.SysCode;
    "isNonData": boolean;
    "codeDataType": sys_core.SysCode;
    "classProps"?: string | null;
    "exprStorageKey"?: string | null;
    "headerSide"?: string | null;
    "isExcludeInsert": boolean;
    "isExcludeSelect": boolean;
    "isExcludeUpdate": boolean;
    "isMultiSelect": boolean;
    "isSelfReference": boolean;
    "matchColumn"?: string | null;
    "maxLength"?: number | null;
    "maxValue"?: number | null;
    "minLength"?: number | null;
    "minValue"?: number | null;
    "pattern"?: string | null;
    "patternMsg"?: string | null;
    "patternReplacement"?: string | null;
    "placeHolder"?: string | null;
    "spinStep"?: string | null;
    "togglePresetTrue"?: boolean | null;
    "toggleValueFalse"?: string | null;
    "toggleValueShow"?: boolean | null;
    "toggleValueTrue"?: string | null;
  }
  export interface SysTable extends sys_core.SysObj {
    "columns": SysColumn[];
    "hasMgmt": boolean;
    "mod": string;
  }
}
export namespace sys_migr {
  export interface SysMigr extends sys_core.SysObj {
    "tablesSource": SysMigrSourceTable[];
    "tablesTarget": SysMigrTargetTable[];
    "description"?: string | null;
  }
  export interface SysMigrSourceColumn extends sys_user.Mgmt {
    "codeDataType": sys_core.SysCode;
    "name": string;
  }
  export interface SysMigrSourceTable extends sys_user.Mgmt {
    "codeMigrSourceType": sys_core.SysCode;
    "columns": SysMigrSourceColumn[];
    "exprSelect"?: string | null;
    "name": string;
  }
  export interface SysMigrTargetColumn extends sys_user.Mgmt {
    "column": sys_db.SysColumn;
    "expr": string;
    "isActive"?: boolean | null;
    "orderDefine": number;
  }
  export interface SysMigrTargetTable extends sys_user.Mgmt {
    "table": sys_db.SysTable;
    "columns": SysMigrTargetColumn[];
    "isActive"?: boolean | null;
    "isInitTable"?: boolean | null;
    "orderDefine": number;
  }
}
export namespace sys_rep {
  export interface SysAnalytic extends sys_core.SysObj {
    "parms": SysRepParm[];
    "statuses": SysAnalyticStatus[];
    "description"?: string | null;
  }
  export interface SysAnalyticStatus extends sys_user.Mgmt {
    "codeStatus": sys_core.SysCode;
    "comment"?: string | null;
    "expr"?: string | null;
  }
  export interface SysRep extends sys_core.SysObj {
    "elements": SysRepEl[];
    "parms": SysRepParm[];
    "actionFieldGroup": sys_core.SysDataObjActionFieldGroup;
    "tables": sys_core.SysDataObjTable[];
    "analytics": SysAnalytic[];
    "description"?: string | null;
    "exprFilter"?: string | null;
    "exprObject"?: string | null;
    "exprSort"?: string | null;
  }
  export interface SysRepEl extends sys_user.Mgmt {
    "codeAlignment"?: sys_core.SysCode | null;
    "codeDataType"?: sys_core.SysCode | null;
    "column"?: sys_db.SysColumn | null;
    "description"?: string | null;
    "header"?: string | null;
    "indexTable"?: number | null;
    "codeSortDir"?: sys_core.SysCode | null;
    "orderSort"?: number | null;
    "codeDbDataSourceValue"?: sys_core.SysCode | null;
    "codeFieldElement"?: sys_core.SysCode | null;
    "codeReportElementType": sys_core.SysCode;
    "exprCustom"?: string | null;
    "nameCustom"?: string | null;
    "isDisplayable"?: boolean | null;
    "orderDefine": number;
    "orderDisplay"?: number | null;
    "isDisplay"?: boolean | null;
  }
  export interface SysRepParm extends sys_user.Mgmt {
    "fieldListItems"?: sys_core.SysDataObjFieldListItems | null;
    "linkTable"?: sys_db.SysTable | null;
    "description"?: string | null;
    "fieldListItemsParmName"?: string | null;
    "header": string;
    "isMultiSelect": boolean;
    "name": string;
    "codeFieldElement": sys_core.SysCode;
    "codeDataType": sys_core.SysCode;
    "orderDefine": number;
  }
  export interface SysRepUser extends sys_user.Mgmt {
    "elements": SysRepUserEl[];
    "parms": SysRepUserParm[];
    "user": sys_user.SysUser;
    "descriptionUser"?: string | null;
    "report": SysRep;
    "analytics": SysRepUserAnalytic[];
    "orderDefine": number;
    "headerUser": string;
  }
  export interface SysRepUserAnalytic extends sys_user.Mgmt {
    "analytic": SysAnalytic;
    "parms": SysRepUserParm[];
  }
  export interface SysRepUserEl extends sys_user.Mgmt {
    "element": SysRepEl;
    "orderDisplay"?: number | null;
    "isDisplay": boolean;
  }
  export interface SysRepUserParm extends sys_user.Mgmt {
    "parm": SysRepParm;
    "parmValue"?: unknown | null;
  }
}
export namespace sys_test {
  export interface Movie extends std.$Object {
    "actors": Person[];
    "title"?: string | null;
  }
  export interface Person extends std.$Object {
    "name": string;
  }
}
export interface types {
  "std": {
    "BaseObject": std.BaseObject;
    "Object": std.$Object;
    "Endian": std.Endian;
    "FreeObject": std.FreeObject;
    "JsonEmpty": std.JsonEmpty;
    "enc": {
      "Base64Alphabet": std.enc.Base64Alphabet;
    };
  };
  "sys_user": {
    "Mgmt": sys_user.Mgmt;
    "UserRoot": sys_user.UserRoot;
    "SysUser": sys_user.SysUser;
    "SYS_USER": sys_user.SYS_USER;
    "SYS_USER_ID": sys_user.SYS_USER_ID;
    "SysStaff": sys_user.SysStaff;
    "SysUserType": sys_user.SysUserType;
    "SysUserTypeResource": sys_user.SysUserTypeResource;
    "SysUserTypeTag": sys_user.SysUserTypeTag;
    "SysWidget": sys_user.SysWidget;
    "currentUser": sys_user.currentUser;
  };
  "app_cm": {
    "CmClient": app_cm.CmClient;
    "CmClientServiceFlow": app_cm.CmClientServiceFlow;
    "CmCohort": app_cm.CmCohort;
    "CmCohortAttd": app_cm.CmCohortAttd;
    "CmCourse": app_cm.CmCourse;
    "CmCsfData": app_cm.CmCsfData;
    "CmCsfCohort": app_cm.CmCsfCohort;
    "CmCsfCohortAttd": app_cm.CmCsfCohortAttd;
    "CmCsfDocument": app_cm.CmCsfDocument;
    "CmCsfJobPlacement": app_cm.CmCsfJobPlacement;
    "CmCsfNote": app_cm.CmCsfNote;
    "CmCsfSchoolPlacement": app_cm.CmCsfSchoolPlacement;
    "CmServiceFlow": app_cm.CmServiceFlow;
  };
  "sys_core": {
    "ObjRoot": sys_core.ObjRoot;
    "SysObj": sys_core.SysObj;
    "SysCode": sys_core.SysCode;
    "SysCodeType": sys_core.SysCodeType;
    "SysDataObj": sys_core.SysDataObj;
    "SysDataObjActionField": sys_core.SysDataObjActionField;
    "SysDataObjActionFieldConfirm": sys_core.SysDataObjActionFieldConfirm;
    "SysDataObjActionFieldGroup": sys_core.SysDataObjActionFieldGroup;
    "SysDataObjActionFieldGroupItem": sys_core.SysDataObjActionFieldGroupItem;
    "SysDataObjActionFieldShow": sys_core.SysDataObjActionFieldShow;
    "SysDataObjActionQuery": sys_core.SysDataObjActionQuery;
    "SysDataObjActionQueryParm": sys_core.SysDataObjActionQueryParm;
    "SysDataObjActionQueryTrigger": sys_core.SysDataObjActionQueryTrigger;
    "SysDataObjColumn": sys_core.SysDataObjColumn;
    "SysDataObjColumnItem": sys_core.SysDataObjColumnItem;
    "SysDataObjColumnLink": sys_core.SysDataObjColumnLink;
    "SysDataObjFieldEmbedListConfig": sys_core.SysDataObjFieldEmbedListConfig;
    "SysDataObjFieldEmbedListEdit": sys_core.SysDataObjFieldEmbedListEdit;
    "SysDataObjFieldEmbedListSelect": sys_core.SysDataObjFieldEmbedListSelect;
    "SysDataObjFieldListItems": sys_core.SysDataObjFieldListItems;
    "SysDataObjTable": sys_core.SysDataObjTable;
    "SysDataObjWith": sys_core.SysDataObjWith;
    "SysEnt": sys_core.SysEnt;
    "SysNodeObj": sys_core.SysNodeObj;
    "SysOrg": sys_core.SysOrg;
    "SysResource": sys_core.SysResource;
  };
  "default": {
    "Movie": Movie;
    "Person": Person;
    "SysError": SysError;
    "SysPerson": SysPerson;
    "SysPersonTest": SysPersonTest;
  };
  "cfg": {
    "ConfigObject": cfg.ConfigObject;
    "AbstractConfig": cfg.AbstractConfig;
    "AllowBareDDL": cfg.AllowBareDDL;
    "Auth": cfg.Auth;
    "AuthMethod": cfg.AuthMethod;
    "DatabaseConfig": cfg.DatabaseConfig;
    "BranchConfig": cfg.BranchConfig;
    "Config": cfg.Config;
    "ConnectionTransport": cfg.ConnectionTransport;
    "ExtensionConfig": cfg.ExtensionConfig;
    "InstanceConfig": cfg.InstanceConfig;
    "JWT": cfg.JWT;
    "Password": cfg.Password;
    "QueryCacheMode": cfg.QueryCacheMode;
    "SCRAM": cfg.SCRAM;
    "Trust": cfg.Trust;
    "mTLS": cfg.mTLS;
  };
  "fts": {
    "ElasticLanguage": fts.ElasticLanguage;
    "Language": fts.Language;
    "LuceneLanguage": fts.LuceneLanguage;
    "PGLanguage": fts.PGLanguage;
    "Weight": fts.Weight;
  };
  "schema": {
    "AccessKind": schema.AccessKind;
    "Object": schema.$Object;
    "SubclassableObject": schema.SubclassableObject;
    "InheritingObject": schema.InheritingObject;
    "AnnotationSubject": schema.AnnotationSubject;
    "AccessPolicy": schema.AccessPolicy;
    "AccessPolicyAction": schema.AccessPolicyAction;
    "Alias": schema.Alias;
    "Annotation": schema.Annotation;
    "Type": schema.Type;
    "PrimitiveType": schema.PrimitiveType;
    "CollectionType": schema.CollectionType;
    "Array": schema.Array;
    "ArrayExprAlias": schema.ArrayExprAlias;
    "CallableObject": schema.CallableObject;
    "Cardinality": schema.Cardinality;
    "VolatilitySubject": schema.VolatilitySubject;
    "Cast": schema.Cast;
    "ConsistencySubject": schema.ConsistencySubject;
    "Constraint": schema.Constraint;
    "Delta": schema.Delta;
    "Extension": schema.Extension;
    "Function": schema.Function;
    "FutureBehavior": schema.FutureBehavior;
    "Global": schema.Global;
    "Index": schema.Index;
    "Pointer": schema.Pointer;
    "Source": schema.Source;
    "Link": schema.Link;
    "Migration": schema.Migration;
    "MigrationGeneratedBy": schema.MigrationGeneratedBy;
    "Module": schema.Module;
    "MultiRange": schema.MultiRange;
    "MultiRangeExprAlias": schema.MultiRangeExprAlias;
    "ObjectType": schema.ObjectType;
    "Operator": schema.Operator;
    "OperatorKind": schema.OperatorKind;
    "Parameter": schema.Parameter;
    "ParameterKind": schema.ParameterKind;
    "Property": schema.Property;
    "PseudoType": schema.PseudoType;
    "Range": schema.Range;
    "RangeExprAlias": schema.RangeExprAlias;
    "Rewrite": schema.Rewrite;
    "RewriteKind": schema.RewriteKind;
    "ScalarType": schema.ScalarType;
    "SourceDeleteAction": schema.SourceDeleteAction;
    "TargetDeleteAction": schema.TargetDeleteAction;
    "Trigger": schema.Trigger;
    "TriggerKind": schema.TriggerKind;
    "TriggerScope": schema.TriggerScope;
    "TriggerTiming": schema.TriggerTiming;
    "Tuple": schema.Tuple;
    "TupleElement": schema.TupleElement;
    "TupleExprAlias": schema.TupleExprAlias;
    "TypeModifier": schema.TypeModifier;
    "Volatility": schema.Volatility;
  };
  "sys": {
    "SystemObject": sys.SystemObject;
    "ExternalObject": sys.ExternalObject;
    "Database": sys.Database;
    "ExtensionPackage": sys.ExtensionPackage;
    "Role": sys.Role;
    "TransactionIsolation": sys.TransactionIsolation;
    "VersionStage": sys.VersionStage;
  };
  "sys_db": {
    "SysColumn": sys_db.SysColumn;
    "SysTable": sys_db.SysTable;
  };
  "sys_migr": {
    "SysMigr": sys_migr.SysMigr;
    "SysMigrSourceColumn": sys_migr.SysMigrSourceColumn;
    "SysMigrSourceTable": sys_migr.SysMigrSourceTable;
    "SysMigrTargetColumn": sys_migr.SysMigrTargetColumn;
    "SysMigrTargetTable": sys_migr.SysMigrTargetTable;
  };
  "sys_rep": {
    "SysAnalytic": sys_rep.SysAnalytic;
    "SysAnalyticStatus": sys_rep.SysAnalyticStatus;
    "SysRep": sys_rep.SysRep;
    "SysRepEl": sys_rep.SysRepEl;
    "SysRepParm": sys_rep.SysRepParm;
    "SysRepUser": sys_rep.SysRepUser;
    "SysRepUserAnalytic": sys_rep.SysRepUserAnalytic;
    "SysRepUserEl": sys_rep.SysRepUserEl;
    "SysRepUserParm": sys_rep.SysRepUserParm;
  };
  "sys_test": {
    "Movie": sys_test.Movie;
    "Person": sys_test.Person;
  };
}


export namespace helper {
  type LinkType = std.BaseObject | std.BaseObject[];

  export type propertyKeys<T> = {
    [k in keyof T]: NonNullable<T[k]> extends LinkType ? never : k;
  }[keyof T];

  export type linkKeys<T> = {
    [k in keyof T]: NonNullable<T[k]> extends LinkType ? k : never;
  }[keyof T];

  export type Props<T> = Pick<T, propertyKeys<T>>;
  export type Links<T> = Pick<T, linkKeys<T>>;
}
