// GENERATED by @gel/generate v0.6.2

export * from "./external";
export { createClient } from "gel";
import * as $ from "./reflection";
import * as $syntax from "./syntax";
import * as $op from "./operators";
import _std from "./modules/std";
import _cfg from "./modules/cfg";
import _default from "./modules/default";
import _schema from "./modules/schema";
import _sys from "./modules/sys";
import _sys_user from "./modules/sys_user";
import _app_cm from "./modules/app_cm";
import _sys_core from "./modules/sys_core";
import _app_crm from "./modules/app_crm";
import _org_client_city_baltimore from "./modules/org_client_city_baltimore";
import _sys_db from "./modules/sys_db";
import _sys_migr from "./modules/sys_migr";
import _sys_rep from "./modules/sys_rep";
import _sys_test from "./modules/sys_test";

const ExportDefault: typeof _std & 
  typeof _default & 
  $.util.OmitDollarPrefixed<typeof $syntax> & 
  typeof $op & {
  "std": typeof _std;
  "cfg": typeof _cfg;
  "default": typeof _default;
  "schema": typeof _schema;
  "sys": typeof _sys;
  "sys_user": typeof _sys_user;
  "app_cm": typeof _app_cm;
  "sys_core": typeof _sys_core;
  "app_crm": typeof _app_crm;
  "org_client_city_baltimore": typeof _org_client_city_baltimore;
  "sys_db": typeof _sys_db;
  "sys_migr": typeof _sys_migr;
  "sys_rep": typeof _sys_rep;
  "sys_test": typeof _sys_test;
} = {
  ..._std,
  ..._default,
  ...$.util.omitDollarPrefixed($syntax),
  ...$op,
  "std": _std,
  "cfg": _cfg,
  "default": _default,
  "schema": _schema,
  "sys": _sys,
  "sys_user": _sys_user,
  "app_cm": _app_cm,
  "sys_core": _sys_core,
  "app_crm": _app_crm,
  "org_client_city_baltimore": _org_client_city_baltimore,
  "sys_db": _sys_db,
  "sys_migr": _sys_migr,
  "sys_rep": _sys_rep,
  "sys_test": _sys_test,
};
const Cardinality = $.Cardinality;
type Cardinality = $.Cardinality;
export type Set<
  Type extends $.BaseType,
  Card extends $.Cardinality = $.Cardinality.Many
> = $.TypeSet<Type, Card>;


export default ExportDefault;
export { Cardinality };
