// GENERATED by @gel/generate v0.6.0

import type * as gel from "gel";
export namespace std {
  export interface BaseObject {
    "id": string;
  }
  export interface $Object extends BaseObject {}
  export type Endian = "Little" | "Big";
  export interface FreeObject extends BaseObject {}
  export type JsonEmpty = "ReturnEmpty" | "ReturnTarget" | "Error" | "UseNull" | "DeleteKey";
  export namespace enc {
    export type Base64Alphabet = "standard" | "urlsafe";
  }
}
export namespace sys_user {
  export interface Mgmt extends std.$Object {
    "createdAt": Date;
    "modifiedAt"?: Date | null;
    "createdBy": SysUser;
    "modifiedBy": SysUser;
  }
  export interface SysUserTypeResource extends sys_core.SysObj {}
  export interface SysApp extends SysUserTypeResource {
    "appHeader": SysAppHeader;
    "nodes": sys_core.SysNodeObj[];
  }
  export interface SysAppHeader extends sys_core.SysObj {}
  export interface SysCodeType extends sys_core.SysObj {
    "parent"?: sys_core.SysCodeType | null;
    "order"?: number | null;
    "valueDecimal"?: number | null;
    "valueInteger"?: number | null;
    "valueString"?: string | null;
  }
  export interface SysTask extends SysUserTypeResource {
    "noDataMsg"?: string | null;
    "codeRenderType"?: sys_core.SysCode | null;
    "codeStatusObj"?: sys_core.SysCode | null;
    "pageDataObj"?: sys_core.SysDataObj | null;
    "targetDataObj"?: sys_core.SysDataObj | null;
    "targetNodeObj"?: sys_core.SysNodeObj | null;
    "description"?: string | null;
    "exprShow"?: string | null;
    "exprStatus"?: string | null;
    "hasAltOpen"?: boolean | null;
    "isPinToDash"?: boolean | null;
  }
  export interface SysUser extends Mgmt {
    "userName"?: string | null;
    "defaultOrg": sys_core.SysOrg;
    "defaultSystem": sys_core.SysSystem;
    "orgs": sys_core.SysOrg[];
    "owner": sys_core.SysOrg;
    "systems": sys_core.SysSystem[];
    "password": string;
    "userTypes": SysUserType[];
    "person": $default.SysPerson;
  }
  export interface SysUserAction extends sys_core.SysObj {
    "actionConfirms": SysUserActionConfirm[];
    "actionShows": SysUserActionShow[];
    "codeAction": sys_core.SysCodeAction;
    "codeTriggerEnable": sys_core.SysCode;
  }
  export interface SysUserActionConfirm extends Mgmt {
    "codeConfirmType": sys_core.SysCode;
    "codeTriggerConfirmConditional": sys_core.SysCode;
    "confirmButtonLabelCancel"?: string | null;
    "confirmButtonLabelConfirm"?: string | null;
    "confirmMessage"?: string | null;
    "confirmTitle"?: string | null;
  }
  export interface SysUserActionShow extends Mgmt {
    "codeExprOp"?: sys_core.SysCode | null;
    "exprField"?: string | null;
    "exprValue"?: string | null;
    "codeTriggerShow": sys_core.SysCode;
    "isRequired": boolean;
  }
  export interface SysUserPref extends Mgmt {
    "user": SysUser;
    "idFeature": string;
    "data": unknown;
  }
  export interface SysUserPrefType extends Mgmt {
    "codeType": sys_core.SysCode;
    "user": SysUser;
    "isActive": boolean;
  }
  export interface SysUserType extends sys_core.SysObj {
    "resources": SysUserTypeResource[];
    "tags": sys_core.SysCode[];
    "isSelfSignup"?: boolean | null;
    "users": SysUser[];
  }
  export interface currentUser extends SysUser {}
}
export namespace app_cm {
  export interface CmClient extends sys_user.Mgmt {
    "person": $default.SysPerson;
    "codeHighestEducation"?: sys_core.SysCode | null;
    "owner": sys_core.SysSystem;
    "agencyId"?: string | null;
    "hasDriversLicense"?: boolean | null;
    "school"?: string | null;
  }
  export interface CmClientServiceFlow extends sys_user.Mgmt {
    "programCm": CmProgram;
    "client": CmClient;
    "codeServiceFlowOutcome"?: sys_core.SysCode | null;
    "codeServiceFlowType"?: sys_core.SysCode | null;
    "codeStatus"?: sys_core.SysCode | null;
    "user"?: sys_user.SysUser | null;
    "dateCreated": gel.LocalDate;
    "dateEnd"?: gel.LocalDate | null;
    "dateEndEst"?: gel.LocalDate | null;
    "dateStart"?: gel.LocalDate | null;
    "dateStartEst"?: gel.LocalDate | null;
    "idxDemo"?: number | null;
    "note"?: string | null;
  }
  export interface CmCohort extends sys_core.SysObj {
    "codeStatus"?: sys_core.SysCode | null;
    "staffInstructor"?: sys_user.SysUser | null;
    "capacity"?: number | null;
    "cost"?: number | null;
    "dateEnd"?: gel.LocalDate | null;
    "dateStart"?: gel.LocalDate | null;
    "isCohortRequired"?: string | null;
    "schedule"?: string | null;
    "cohortAttds": CmCohortAttd[];
    "course"?: CmCourse | null;
  }
  export interface CmCohortAttd extends sys_user.Mgmt {
    "date": gel.LocalDate;
    "file"?: unknown | null;
    "hours": number;
    "note"?: string | null;
    "cohortId"?: string | null;
  }
  export interface CmCohortDoc extends sys_user.Mgmt {
    "cohort": CmCohort;
    "codeType": sys_core.SysCode;
    "date": gel.LocalDate;
    "file"?: unknown | null;
    "note"?: string | null;
  }
  export interface CmCourse extends sys_core.SysObj {
    "courseCertifications"?: string | null;
    "courseExams"?: string | null;
    "courseItemsIncluded"?: string | null;
    "courseItemsNotIncluded"?: string | null;
    "courseRequirements"?: string | null;
    "description"?: string | null;
    "schedule"?: string | null;
    "cohorts": CmCohort[];
    "codeSector"?: sys_core.SysCode | null;
    "codeStatus"?: sys_core.SysCode | null;
    "codeTypePayment"?: sys_core.SysCodeType | null;
  }
  export interface CmCsfData extends sys_user.Mgmt {
    "csf": CmClientServiceFlow;
  }
  export interface CmCsfCohort extends CmCsfData {
    "codeStatus": sys_core.SysCode;
    "note"?: string | null;
    "cohort": CmCohort;
  }
  export interface CmCsfCohortAttd extends sys_user.Mgmt {
    "codeCmCohortAttdDuration": sys_core.SysCode;
    "cohortAttd": CmCohortAttd;
    "computedHours"?: number | null;
    "csfCohort": CmCsfCohort;
    "note"?: string | null;
  }
  export interface CmCsfDocument extends CmCsfData {
    "codeType": sys_core.SysCode;
    "dateExpires"?: gel.LocalDate | null;
    "dateIssued": gel.LocalDate;
    "file"?: unknown | null;
    "isShareWithClient"?: boolean | null;
    "note"?: string | null;
  }
  export interface CmCsfGroup extends CmCsfData {
    "cmGroup": CmGroup;
  }
  export interface CmCsfJobPlacement extends CmCsfData {
    "codeJobType": sys_core.SysCode;
    "codePlacementRelated": sys_core.SysCode;
    "codeRetention"?: sys_core.SysCode | null;
    "codeWageType": sys_core.SysCode;
    "dateStart": gel.LocalDate;
    "employerContactEmail"?: string | null;
    "employerContactNameFirst"?: string | null;
    "employerContactNameLast"?: string | null;
    "employerContactPhone"?: string | null;
    "employerName": string;
    "hoursPerWeek": number;
    "note"?: string | null;
    "title": string;
    "wage"?: number | null;
  }
  export interface CmCsfNote extends CmCsfData {
    "codeType": sys_core.SysCode;
    "date": gel.LocalDate;
    "note"?: string | null;
  }
  export interface CmCsfSchoolPlacement extends CmCsfData {
    "codeCollegeStatus": sys_core.SysCode;
    "collegeGPA"?: string | null;
    "collegeGradYear"?: number | null;
    "collegeMajor"?: string | null;
    "collegeName"?: string | null;
    "date": gel.LocalDate;
    "note"?: string | null;
  }
  export interface CmGroup extends sys_core.SysObj {
    "userGroupMgr"?: sys_user.SysUser | null;
    "codeGroupEnrollment": sys_core.SysCode;
    "codeGroupType": sys_core.SysCode;
    "dateEnd"?: gel.LocalDate | null;
    "dateStart": gel.LocalDate;
    "isActive": boolean;
  }
  export interface CmPartner extends sys_core.SysObjEnt {}
  export interface CmProgram extends sys_core.SysObj {}
}
export namespace $default {
  export interface SysError extends std.$Object {
    "user": sys_user.SysUser;
    "createdAt": Date;
    "errFile"?: string | null;
    "errFunction"?: string | null;
    "errMsg"?: string | null;
  }
  export interface SysPerson extends sys_core.ObjRoot {
    "codeState"?: sys_core.SysCode | null;
    "addr1"?: string | null;
    "addr2"?: string | null;
    "avatar"?: unknown | null;
    "city"?: string | null;
    "email"?: string | null;
    "zip"?: string | null;
    "genderSelfId"?: string | null;
    "codeDisabilityStatus"?: sys_core.SysCode | null;
    "codeEthnicity"?: sys_core.SysCode | null;
    "codeGender"?: sys_core.SysCode | null;
    "codeRace"?: sys_core.SysCode | null;
    "birthDate"?: gel.LocalDate | null;
    "favFood"?: string | null;
    "firstName": string;
    "lastName": string;
    "fullName": string;
    "idMigration"?: string | null;
    "isLegalAgreed"?: boolean | null;
    "middleName"?: string | null;
    "phoneAlt"?: string | null;
    "phoneMobile"?: string | null;
    "ssn"?: string | null;
    "title"?: string | null;
  }
}
export type SysError = $default.SysError;
export type SysPerson = $default.SysPerson;
export namespace sys_core {
  export interface ObjRoot extends std.$Object {
    "note"?: string | null;
    "testText"?: string | null;
    "attributes": SysAttr[];
    "testCodeMulti": SysCode[];
    "testCodeSingle"?: SysCode | null;
    "testBool"?: boolean | null;
    "testDate"?: gel.LocalDate | null;
    "testDateTime"?: gel.LocalDateTime | null;
    "testNumberFloat"?: number | null;
    "testNumberInt"?: number | null;
  }
  export interface ObjRootCore extends ObjRoot {
    "codeObjType"?: SysCode | null;
    "codeIcon"?: SysCode | null;
    "orderDefine"?: number | null;
    "header"?: string | null;
    "name": string;
  }
  export interface SysObj extends ObjRootCore, sys_user.Mgmt {
    "isGlobalResource"?: boolean | null;
    "owner": SysSystem;
  }
  export interface SysObjEnt extends SysObj {
    "codeState"?: SysCode | null;
    "addr1"?: string | null;
    "addr2"?: string | null;
    "city"?: string | null;
    "email"?: string | null;
    "website"?: string | null;
    "zip"?: string | null;
    "contacts": $default.SysPerson[];
    "notes": SysObjNote[];
  }
  export interface SysAttr extends sys_user.Mgmt {
    "obj": SysObjEntAttr;
    "hasAccess": boolean;
  }
  export interface SysCode extends ObjRootCore, sys_user.Mgmt {
    "valueDecimal"?: number | null;
    "parent"?: SysCode | null;
    "order"?: number | null;
    "valueInteger"?: number | null;
    "valueString"?: string | null;
    "codeType": SysCodeType;
    "owner": SysSystem;
    "codeTypeFamily": SysCodeType[];
  }
  export interface SysCodeAction extends SysCode {}
  export interface SysCodeType extends SysObj {
    "parent"?: SysCodeType | null;
    "order"?: number | null;
    "valueDecimal"?: number | null;
    "valueInteger"?: number | null;
    "valueString"?: string | null;
  }
  export interface SysDataObj extends SysObj {
    "actionGroup"?: SysDataObjActionGroup | null;
    "isInitialValidationSilent"?: boolean | null;
    "codeCardinality": SysCode;
    "codeComponent": SysCode;
    "codeDataObjType"?: SysCode | null;
    "codeListEditPresetType"?: SysCode | null;
    "processType"?: SysCode | null;
    "description"?: string | null;
    "exprFilter"?: string | null;
    "exprSort"?: string | null;
    "exprWith"?: string | null;
    "isDetailRetrievePreset"?: boolean | null;
    "isListEdit": boolean;
    "isListSuppressFilterSort"?: boolean | null;
    "isListSuppressSelect"?: boolean | null;
    "listEditPresetExpr"?: string | null;
    "parentFilterExpr"?: string | null;
    "subHeader"?: string | null;
    "isRetrieveReadonly"?: boolean | null;
    "queryRiders": SysDataObjQueryRider[];
    "columns": SysDataObjColumn[];
    "listReorderColumn"?: sys_db.SysColumn | null;
    "parentColumn"?: sys_db.SysColumn | null;
    "parentTable"?: sys_db.SysTable | null;
    "tables": SysDataObjTable[];
  }
  export interface SysDataObjAction extends sys_user.Mgmt {
    "codeColor": SysCode;
    "orderDefine": number;
    "action": sys_user.SysUserAction;
    "isListRowAction": boolean;
  }
  export interface SysDataObjActionGroup extends SysObj {
    "dataObjActions": SysDataObjAction[];
  }
  export interface SysDataObjColumn extends sys_user.Mgmt {
    "exprSave"?: string | null;
    "inputMaskAlt"?: string | null;
    "fieldListItemsParmValue"?: string | null;
    "file"?: unknown | null;
    "exprSaveAttrObjects"?: string | null;
    "codeAttrType"?: SysCode | null;
    "attrAccess"?: boolean | null;
    "itemChanges": SysDataObjColumnItemChange[];
    "codeAccess"?: SysCode | null;
    "codeAlignmentAlt"?: SysCode | null;
    "codeColor"?: SysCode | null;
    "codeDbDataSourceValue"?: SysCode | null;
    "codeFieldElement"?: SysCode | null;
    "codeSortDir"?: SysCode | null;
    "column": sys_db.SysColumn;
    "columnBacklink"?: sys_db.SysColumn | null;
    "customEmbedShellFields": SysDataObjColumn[];
    "fieldEmbedListConfig"?: SysDataObjFieldEmbedListConfig | null;
    "fieldEmbedListEdit"?: SysDataObjFieldEmbedListEdit | null;
    "fieldEmbedListSelect"?: SysDataObjFieldEmbedListSelect | null;
    "fieldListItems"?: SysDataObjFieldListItems | null;
    "items": SysDataObjColumnItemValue[];
    "linkColumns": SysDataObjColumnLink[];
    "linkTable"?: sys_db.SysTable | null;
    "customColActionValue"?: string | null;
    "customColAlign"?: string | null;
    "customColIsSubHeader"?: boolean | null;
    "customColLabel"?: string | null;
    "customColPrefix"?: string | null;
    "customColRawHTML"?: string | null;
    "customColSize"?: string | null;
    "customColSource"?: string | null;
    "customColSourceKey"?: string | null;
    "exprCustom"?: string | null;
    "exprPreset"?: string | null;
    "headerAlt"?: string | null;
    "height"?: number | null;
    "indexTable"?: number | null;
    "isDisplay"?: boolean | null;
    "isDisplayBlock"?: boolean | null;
    "isDisplayable"?: boolean | null;
    "isExcludeInsert": boolean;
    "isExcludeSelect": boolean;
    "isExcludeUpdate": boolean;
    "nameCustom"?: string | null;
    "orderCrumb"?: number | null;
    "orderDefine": number;
    "orderDisplay"?: number | null;
    "orderSort"?: number | null;
    "width"?: number | null;
    "action"?: sys_user.SysUserAction | null;
  }
  export interface SysDataObjColumnItemChange extends sys_user.Mgmt {
    "codeAccess"?: SysCode | null;
    "codeValueTarget"?: SysCode | null;
    "codeValueTrigger"?: SysCode | null;
    "column": SysDataObjColumn;
    "valueScalarTarget"?: string | null;
    "valueScalarTrigger"?: string | null;
    "selectParmValue"?: string | null;
    "orderDefine": number;
    "codeOp"?: SysCode | null;
    "codeValueTypeTarget": SysCode;
    "codeValueTypeTrigger": SysCode;
  }
  export interface SysDataObjColumnItemValue extends sys_user.Mgmt {
    "data": string;
    "display": string;
    "orderDefine": number;
  }
  export interface SysDataObjColumnLink extends sys_user.Mgmt {
    "column": sys_db.SysColumn;
    "orderDefine": number;
  }
  export interface SysDataObjFieldEmbedListConfig extends SysObj {
    "actionGroupModal": SysDataObjActionGroup;
    "dataObjEmbed": SysDataObj;
    "dataObjModal": SysDataObj;
  }
  export interface SysDataObjFieldEmbedListEdit extends SysObj {
    "dataObjEmbed": SysDataObj;
  }
  export interface SysDataObjFieldEmbedListSelect extends SysObj {
    "actionGroupModal": SysDataObjActionGroup;
    "dataObjList": SysDataObj;
    "btnLabelComplete": string;
  }
  export interface SysDataObjFieldListItems extends SysObj {
    "codeDataTypeDisplay"?: SysCode | null;
    "codeMask"?: SysCode | null;
    "props": SysDataObjFieldListItemsProp[];
    "displayIdSeparator"?: string | null;
    "exprFilter"?: string | null;
    "exprSort"?: string | null;
    "exprWith"?: string | null;
    "table"?: sys_db.SysTable | null;
  }
  export interface SysDataObjFieldListItemsProp extends std.$Object {
    "expr": string;
    "header": string;
    "isDisplayId": boolean;
    "key": string;
    "orderDefine": number;
    "orderSort"?: number | null;
  }
  export interface SysDataObjQueryRider extends sys_user.Mgmt {
    "codeQueryType": SysCode;
    "codeTriggerTiming": SysCode;
    "codeUserDestination"?: SysCode | null;
    "codeUserMsgDelivery"?: SysCode | null;
    "userMsg"?: string | null;
    "codeFunction"?: SysCode | null;
    "functionParmValue"?: string | null;
    "expr"?: string | null;
    "codeType": SysCode;
  }
  export interface SysDataObjTable extends sys_user.Mgmt {
    "columnParent"?: sys_db.SysColumn | null;
    "columnsId": sys_db.SysColumn[];
    "table": sys_db.SysTable;
    "exprFilterUpdate"?: string | null;
    "index": number;
    "indexParent"?: number | null;
    "isTableExtension"?: boolean | null;
  }
  export interface SysDataObjWith extends sys_user.Mgmt {
    "expr": string;
    "index": number;
  }
  export interface SysMsg extends ObjRoot {
    "responses": SysMsg[];
    "parent"?: SysMsg | null;
    "subject"?: string | null;
    "date"?: gel.LocalDate | null;
    "readers": $default.SysPerson[];
    "createdAt": Date;
    "recipients": $default.SysPerson[];
    "sender": $default.SysPerson;
    "codeStatus"?: SysCode | null;
    "isRead": boolean;
  }
  export interface SysNodeObj extends SysObj {
    "children": SysNodeObj[];
    "codeNavType": SysCode;
    "codeNodeType": SysCode;
    "isAlwaysRetrieveData": boolean;
    "isHideRowManager": boolean;
    "page"?: string | null;
    "data": SysNodeObjData[];
    "parent"?: SysNodeObj | null;
  }
  export interface SysNodeObjData extends std.$Object {
    "dataObj": SysDataObj;
    "codeAction": SysCodeAction;
  }
  export interface SysNotify extends SysObj {
    "codeNotifyType": SysCode;
    "exprCron": string;
    "exprData"?: string | null;
    "exprTrigger": string;
    "msg"?: string | null;
  }
  export interface SysObjEntAttr extends SysObjEnt {}
  export interface SysObjNote extends sys_user.Mgmt {
    "codeType": SysCode;
    "date": gel.LocalDate;
    "note"?: string | null;
  }
  export interface SysOrg extends ObjRootCore, sys_user.Mgmt {
    "users": sys_user.SysUser[];
  }
  export interface SysSystem extends ObjRootCore, sys_user.Mgmt {
    "appName"?: string | null;
    "file"?: unknown | null;
    "logoMarginRight"?: number | null;
    "logoWidth"?: number | null;
    "owner": SysOrg;
  }
}
export namespace app_crm {
  export interface CrmClient extends sys_core.SysObjEnt {}
}
export namespace cfg {
  export interface ConfigObject extends std.BaseObject {}
  export interface AbstractConfig extends ConfigObject {
    "extensions": ExtensionConfig[];
    "session_idle_timeout": gel.Duration;
    "session_idle_transaction_timeout": gel.Duration;
    "query_execution_timeout": gel.Duration;
    "listen_port": number;
    "listen_addresses": string[];
    "auth": Auth[];
    "allow_dml_in_functions"?: boolean | null;
    "allow_bare_ddl"?: AllowBareDDL | null;
    "apply_access_policies"?: boolean | null;
    "allow_user_specified_id"?: boolean | null;
    "cors_allow_origins": string[];
    "auto_rebuild_query_cache"?: boolean | null;
    "auto_rebuild_query_cache_timeout"?: gel.Duration | null;
    "query_cache_mode"?: QueryCacheMode | null;
    "shared_buffers"?: gel.ConfigMemory | null;
    "query_work_mem"?: gel.ConfigMemory | null;
    "maintenance_work_mem"?: gel.ConfigMemory | null;
    "effective_cache_size"?: gel.ConfigMemory | null;
    "effective_io_concurrency"?: number | null;
    "default_statistics_target"?: number | null;
    "force_database_error"?: string | null;
    "_pg_prepared_statement_cache_size": number;
  }
  export type AllowBareDDL = "AlwaysAllow" | "NeverAllow";
  export interface Auth extends ConfigObject {
    "priority": number;
    "user": string[];
    "method"?: AuthMethod | null;
    "comment"?: string | null;
  }
  export interface AuthMethod extends ConfigObject {
    "transports": ConnectionTransport[];
  }
  export interface DatabaseConfig extends AbstractConfig {}
  export interface BranchConfig extends DatabaseConfig {}
  export interface Config extends AbstractConfig {}
  export type ConnectionTransport = "TCP" | "TCP_PG" | "HTTP" | "SIMPLE_HTTP" | "HTTP_METRICS" | "HTTP_HEALTH";
  export interface ExtensionConfig extends ConfigObject {
    "cfg": AbstractConfig;
  }
  export interface InstanceConfig extends AbstractConfig {}
  export interface JWT extends AuthMethod {
    "transports": ConnectionTransport[];
  }
  export interface Password extends AuthMethod {
    "transports": ConnectionTransport[];
  }
  export type QueryCacheMode = "InMemory" | "RegInline" | "PgFunc" | "Default";
  export interface SCRAM extends AuthMethod {
    "transports": ConnectionTransport[];
  }
  export interface Trust extends AuthMethod {}
  export interface mTLS extends AuthMethod {
    "transports": ConnectionTransport[];
  }
}
export namespace fts {
  export type ElasticLanguage = "ara" | "bul" | "cat" | "ces" | "ckb" | "dan" | "deu" | "ell" | "eng" | "eus" | "fas" | "fin" | "fra" | "gle" | "glg" | "hin" | "hun" | "hye" | "ind" | "ita" | "lav" | "nld" | "nor" | "por" | "ron" | "rus" | "spa" | "swe" | "tha" | "tur" | "zho" | "edb_Brazilian" | "edb_ChineseJapaneseKorean";
  export type Language = "ara" | "hye" | "eus" | "cat" | "dan" | "nld" | "eng" | "fin" | "fra" | "deu" | "ell" | "hin" | "hun" | "ind" | "gle" | "ita" | "nor" | "por" | "ron" | "rus" | "spa" | "swe" | "tur";
  export type LuceneLanguage = "ara" | "ben" | "bul" | "cat" | "ces" | "ckb" | "dan" | "deu" | "ell" | "eng" | "est" | "eus" | "fas" | "fin" | "fra" | "gle" | "glg" | "hin" | "hun" | "hye" | "ind" | "ita" | "lav" | "lit" | "nld" | "nor" | "por" | "ron" | "rus" | "spa" | "srp" | "swe" | "tha" | "tur" | "edb_Brazilian" | "edb_ChineseJapaneseKorean" | "edb_Indian";
  export type PGLanguage = "xxx_simple" | "ara" | "hye" | "eus" | "cat" | "dan" | "nld" | "eng" | "fin" | "fra" | "deu" | "ell" | "hin" | "hun" | "ind" | "gle" | "ita" | "lit" | "npi" | "nor" | "por" | "ron" | "rus" | "srp" | "spa" | "swe" | "tam" | "tur" | "yid";
  export type Weight = "A" | "B" | "C" | "D";
}
export namespace org_client_moed {
  export interface MoedPartData extends sys_core.SysObj {
    "participant"?: MoedParticipant | null;
  }
  export interface MoedParticipant extends app_cm.CmClient {
    "consentDisclaimer"?: boolean | null;
    "idxDemo": number;
  }
}
export namespace schema {
  export type AccessKind = "Select" | "UpdateRead" | "UpdateWrite" | "Delete" | "Insert";
  export interface $Object extends std.BaseObject {
    "name": string;
    "internal": boolean;
    "builtin": boolean;
    "computed_fields"?: string[] | null;
  }
  export interface SubclassableObject extends $Object {
    "abstract"?: boolean | null;
    "is_abstract"?: boolean | null;
    "final": boolean;
    "is_final": boolean;
  }
  export interface InheritingObject extends SubclassableObject {
    "bases": InheritingObject[];
    "ancestors": InheritingObject[];
    "inherited_fields"?: string[] | null;
  }
  export interface AnnotationSubject extends $Object {
    "annotations": Annotation[];
  }
  export interface AccessPolicy extends InheritingObject, AnnotationSubject {
    "subject": ObjectType;
    "access_kinds": AccessKind[];
    "condition"?: string | null;
    "action": AccessPolicyAction;
    "expr"?: string | null;
    "errmessage"?: string | null;
  }
  export type AccessPolicyAction = "Allow" | "Deny";
  export interface Alias extends AnnotationSubject {
    "expr": string;
    "type"?: Type | null;
  }
  export interface Annotation extends InheritingObject, AnnotationSubject {
    "inheritable"?: boolean | null;
  }
  export interface Type extends SubclassableObject, AnnotationSubject {
    "expr"?: string | null;
    "from_alias"?: boolean | null;
    "is_from_alias"?: boolean | null;
  }
  export interface PrimitiveType extends Type {}
  export interface CollectionType extends PrimitiveType {}
  export interface Array extends CollectionType {
    "element_type": Type;
    "dimensions"?: number[] | null;
  }
  export interface ArrayExprAlias extends Array {}
  export interface CallableObject extends AnnotationSubject {
    "params": Parameter[];
    "return_type"?: Type | null;
    "return_typemod"?: TypeModifier | null;
  }
  export type Cardinality = "One" | "Many";
  export interface VolatilitySubject extends $Object {
    "volatility"?: Volatility | null;
  }
  export interface Cast extends AnnotationSubject, VolatilitySubject {
    "from_type"?: Type | null;
    "to_type"?: Type | null;
    "allow_implicit"?: boolean | null;
    "allow_assignment"?: boolean | null;
  }
  export interface ConsistencySubject extends InheritingObject, AnnotationSubject {
    "constraints": Constraint[];
  }
  export interface Constraint extends CallableObject, InheritingObject {
    "params": Parameter[];
    "expr"?: string | null;
    "subjectexpr"?: string | null;
    "finalexpr"?: string | null;
    "errmessage"?: string | null;
    "delegated"?: boolean | null;
    "except_expr"?: string | null;
    "subject"?: ConsistencySubject | null;
  }
  export interface Delta extends $Object {
    "parents": Delta[];
  }
  export interface Extension extends AnnotationSubject, $Object {
    "package": sys.ExtensionPackage;
  }
  export interface Function extends CallableObject, VolatilitySubject {
    "preserves_optionality"?: boolean | null;
    "body"?: string | null;
    "language": string;
    "used_globals": Global[];
  }
  export interface FutureBehavior extends $Object {}
  export interface Global extends AnnotationSubject {
    "target"?: Type | null;
    "required"?: boolean | null;
    "cardinality"?: Cardinality | null;
    "expr"?: string | null;
    "default"?: string | null;
  }
  export interface Index extends InheritingObject, AnnotationSubject {
    "expr"?: string | null;
    "except_expr"?: string | null;
    "params": Parameter[];
    "kwargs"?: {name: string, expr: string}[] | null;
  }
  export interface Pointer extends ConsistencySubject, AnnotationSubject {
    "cardinality"?: Cardinality | null;
    "required"?: boolean | null;
    "readonly"?: boolean | null;
    "default"?: string | null;
    "expr"?: string | null;
    "secret"?: boolean | null;
    "source"?: Source | null;
    "target"?: Type | null;
    "rewrites": Rewrite[];
  }
  export interface Source extends $Object {
    "indexes": Index[];
    "pointers": Pointer[];
  }
  export interface Link extends Pointer, Source {
    "target"?: ObjectType | null;
    "properties": Property[];
    "on_target_delete"?: TargetDeleteAction | null;
    "on_source_delete"?: SourceDeleteAction | null;
  }
  export interface Migration extends AnnotationSubject, $Object {
    "parents": Migration[];
    "script": string;
    "message"?: string | null;
    "generated_by"?: MigrationGeneratedBy | null;
  }
  export type MigrationGeneratedBy = "DevMode" | "DDLStatement";
  export interface Module extends AnnotationSubject, $Object {}
  export interface MultiRange extends CollectionType {
    "element_type": Type;
  }
  export interface MultiRangeExprAlias extends MultiRange {}
  export interface ObjectType extends Source, ConsistencySubject, InheritingObject, Type, AnnotationSubject {
    "union_of": ObjectType[];
    "intersection_of": ObjectType[];
    "access_policies": AccessPolicy[];
    "triggers": Trigger[];
    "compound_type": boolean;
    "is_compound_type": boolean;
    "links": Link[];
    "properties": Property[];
  }
  export interface Operator extends CallableObject, VolatilitySubject {
    "operator_kind"?: OperatorKind | null;
    "abstract"?: boolean | null;
    "is_abstract"?: boolean | null;
  }
  export type OperatorKind = "Infix" | "Postfix" | "Prefix" | "Ternary";
  export interface Parameter extends $Object {
    "type": Type;
    "typemod": TypeModifier;
    "kind": ParameterKind;
    "num": number;
    "default"?: string | null;
  }
  export type ParameterKind = "VariadicParam" | "NamedOnlyParam" | "PositionalParam";
  export interface Property extends Pointer {}
  export interface PseudoType extends InheritingObject, Type {}
  export interface Range extends CollectionType {
    "element_type": Type;
  }
  export interface RangeExprAlias extends Range {}
  export interface Rewrite extends InheritingObject, AnnotationSubject {
    "subject": Pointer;
    "kind": TriggerKind;
    "expr": string;
  }
  export type RewriteKind = "Update" | "Insert";
  export interface ScalarType extends PrimitiveType, ConsistencySubject, AnnotationSubject {
    "default"?: string | null;
    "enum_values"?: string[] | null;
    "arg_values"?: string[] | null;
  }
  export type SourceDeleteAction = "DeleteTarget" | "Allow" | "DeleteTargetIfOrphan";
  export type TargetDeleteAction = "Restrict" | "DeleteSource" | "Allow" | "DeferredRestrict";
  export interface Trigger extends InheritingObject, AnnotationSubject {
    "subject": ObjectType;
    "timing": TriggerTiming;
    "kinds": TriggerKind[];
    "scope": TriggerScope;
    "expr"?: string | null;
    "condition"?: string | null;
  }
  export type TriggerKind = "Update" | "Delete" | "Insert";
  export type TriggerScope = "All" | "Each";
  export type TriggerTiming = "After" | "AfterCommitOf";
  export interface Tuple extends CollectionType {
    "named": boolean;
    "element_types": TupleElement[];
  }
  export interface TupleElement extends std.BaseObject {
    "type": Type;
    "name"?: string | null;
  }
  export interface TupleExprAlias extends Tuple {}
  export type TypeModifier = "SetOfType" | "OptionalType" | "SingletonType";
  export type Volatility = "Immutable" | "Stable" | "Volatile";
}
export namespace sys {
  export interface SystemObject extends schema.$Object {}
  export interface ExternalObject extends SystemObject {}
  export interface Database extends ExternalObject, schema.AnnotationSubject {
    "name": string;
  }
  export interface ExtensionPackage extends SystemObject, schema.AnnotationSubject {
    "script": string;
    "version": {major: number, minor: number, stage: VersionStage, stage_no: number, local: string[]};
  }
  export interface Role extends SystemObject, schema.InheritingObject, schema.AnnotationSubject {
    "name": string;
    "superuser": boolean;
    "is_superuser": boolean;
    "password"?: string | null;
    "member_of": Role[];
  }
  export type TransactionIsolation = "RepeatableRead" | "Serializable";
  export type VersionStage = "dev" | "alpha" | "beta" | "rc" | "final";
}
export namespace sys_db {
  export interface SysColumn extends sys_core.SysObj {
    "toggleContinueRequiresTrue"?: boolean | null;
    "inputMask"?: string | null;
    "codeAlignment": sys_core.SysCode;
    "codeDataType": sys_core.SysCode;
    "classProps"?: string | null;
    "exprStorageKey"?: string | null;
    "headerSide"?: string | null;
    "isExcludeInsert": boolean;
    "isExcludeSelect": boolean;
    "isExcludeUpdate": boolean;
    "isMultiSelect": boolean;
    "isSelfReference": boolean;
    "matchColumn"?: string | null;
    "maxLength"?: number | null;
    "maxValue"?: number | null;
    "minLength"?: number | null;
    "minValue"?: number | null;
    "pattern"?: string | null;
    "patternMsg"?: string | null;
    "patternReplacement"?: string | null;
    "placeHolder"?: string | null;
    "spinStep"?: string | null;
    "togglePresetTrue"?: boolean | null;
    "toggleValueFalse"?: string | null;
    "toggleValueShow"?: boolean | null;
    "toggleValueTrue"?: string | null;
    "isFormTag"?: boolean | null;
  }
  export interface SysTable extends sys_core.SysObj {
    "columns": SysColumn[];
    "hasMgmt": boolean;
    "mod": string;
    "table": string;
  }
}
export namespace sys_migr {
  export interface SysMigr extends sys_core.SysObj {
    "tablesSource": SysMigrSourceTable[];
    "tablesTarget": SysMigrTargetTable[];
    "description"?: string | null;
  }
  export interface SysMigrSourceColumn extends sys_user.Mgmt {
    "codeDataType": sys_core.SysCode;
    "name": string;
  }
  export interface SysMigrSourceTable extends sys_user.Mgmt {
    "codeMigrSourceType": sys_core.SysCode;
    "columns": SysMigrSourceColumn[];
    "exprSelect"?: string | null;
    "name": string;
  }
  export interface SysMigrTargetColumn extends sys_user.Mgmt {
    "column": sys_db.SysColumn;
    "expr": string;
    "isActive"?: boolean | null;
    "orderDefine": number;
  }
  export interface SysMigrTargetTable extends sys_user.Mgmt {
    "table": sys_db.SysTable;
    "columns": SysMigrTargetColumn[];
    "isActive"?: boolean | null;
    "isInitTable"?: boolean | null;
    "orderDefine": number;
  }
}
export namespace sys_rep {
  export interface SysAnalytic extends sys_core.SysObj {
    "description"?: string | null;
    "parms": SysRepParm[];
    "statuses": SysAnalyticStatus[];
  }
  export interface SysAnalyticStatus extends sys_user.Mgmt {
    "codeStatus": sys_core.SysCode;
    "comment"?: string | null;
    "expr"?: string | null;
  }
  export interface SysRep extends sys_user.SysUserTypeResource {
    "actionGroup": sys_core.SysDataObjActionGroup;
    "analytics": SysAnalytic[];
    "description"?: string | null;
    "exprFilter"?: string | null;
    "exprSort"?: string | null;
    "exprWith"?: string | null;
    "tables": sys_core.SysDataObjTable[];
    "elements": SysRepEl[];
    "parms": SysRepParm[];
  }
  export interface SysRepEl extends sys_user.Mgmt {
    "codeAlignment"?: sys_core.SysCode | null;
    "codeDataType"?: sys_core.SysCode | null;
    "codeDbDataSourceValue"?: sys_core.SysCode | null;
    "codeFieldElement"?: sys_core.SysCode | null;
    "codeReportElementType": sys_core.SysCode;
    "codeSortDir"?: sys_core.SysCode | null;
    "linkColumns": sys_core.SysDataObjColumnLink[];
    "column"?: sys_db.SysColumn | null;
    "description"?: string | null;
    "exprCustom"?: string | null;
    "header"?: string | null;
    "indexTable"?: number | null;
    "isDisplay"?: boolean | null;
    "isDisplayable"?: boolean | null;
    "nameCustom"?: string | null;
    "orderDefine": number;
    "orderDisplay"?: number | null;
    "orderSort"?: number | null;
  }
  export interface SysRepParm extends sys_user.Mgmt {
    "fieldListItemsParmValue"?: string | null;
    "codeDataType": sys_core.SysCode;
    "codeFieldElement": sys_core.SysCode;
    "fieldListItems"?: sys_core.SysDataObjFieldListItems | null;
    "description"?: string | null;
    "exprFilter"?: string | null;
    "header": string;
    "isMultiSelect": boolean;
    "isRequired": boolean;
    "name": string;
    "orderDefine": number;
  }
  export interface SysRepUser extends sys_user.Mgmt {
    "report": SysRep;
    "analytics": SysRepUserAnalytic[];
    "parms": SysRepUserParm[];
    "user": sys_user.SysUser;
    "descriptionUser"?: string | null;
    "headerUser": string;
    "orderDefine": number;
  }
  export interface SysRepUserAnalytic extends sys_user.Mgmt {
    "analytic": SysAnalytic;
    "parms": SysRepUserParm[];
  }
  export interface SysRepUserParm extends sys_user.Mgmt {
    "parm": SysRepParm;
    "parmValue"?: unknown | null;
  }
}
export namespace sys_test {
  export interface Movie extends std.$Object {
    "actors": Person[];
    "title"?: string | null;
  }
  export interface Person extends std.$Object {
    "name": string;
  }
}
export interface types {
  "std": {
    "BaseObject": std.BaseObject;
    "Object": std.$Object;
    "Endian": std.Endian;
    "FreeObject": std.FreeObject;
    "JsonEmpty": std.JsonEmpty;
    "enc": {
      "Base64Alphabet": std.enc.Base64Alphabet;
    };
  };
  "sys_user": {
    "Mgmt": sys_user.Mgmt;
    "SysUserTypeResource": sys_user.SysUserTypeResource;
    "SysApp": sys_user.SysApp;
    "SysAppHeader": sys_user.SysAppHeader;
    "SysCodeType": sys_user.SysCodeType;
    "SysTask": sys_user.SysTask;
    "SysUser": sys_user.SysUser;
    "SysUserAction": sys_user.SysUserAction;
    "SysUserActionConfirm": sys_user.SysUserActionConfirm;
    "SysUserActionShow": sys_user.SysUserActionShow;
    "SysUserPref": sys_user.SysUserPref;
    "SysUserPrefType": sys_user.SysUserPrefType;
    "SysUserType": sys_user.SysUserType;
    "currentUser": sys_user.currentUser;
  };
  "app_cm": {
    "CmClient": app_cm.CmClient;
    "CmClientServiceFlow": app_cm.CmClientServiceFlow;
    "CmCohort": app_cm.CmCohort;
    "CmCohortAttd": app_cm.CmCohortAttd;
    "CmCohortDoc": app_cm.CmCohortDoc;
    "CmCourse": app_cm.CmCourse;
    "CmCsfData": app_cm.CmCsfData;
    "CmCsfCohort": app_cm.CmCsfCohort;
    "CmCsfCohortAttd": app_cm.CmCsfCohortAttd;
    "CmCsfDocument": app_cm.CmCsfDocument;
    "CmCsfGroup": app_cm.CmCsfGroup;
    "CmCsfJobPlacement": app_cm.CmCsfJobPlacement;
    "CmCsfNote": app_cm.CmCsfNote;
    "CmCsfSchoolPlacement": app_cm.CmCsfSchoolPlacement;
    "CmGroup": app_cm.CmGroup;
    "CmPartner": app_cm.CmPartner;
    "CmProgram": app_cm.CmProgram;
  };
  "default": {
    "SysError": $default.SysError;
    "SysPerson": $default.SysPerson;
  };
  "sys_core": {
    "ObjRoot": sys_core.ObjRoot;
    "ObjRootCore": sys_core.ObjRootCore;
    "SysObj": sys_core.SysObj;
    "SysObjEnt": sys_core.SysObjEnt;
    "SysAttr": sys_core.SysAttr;
    "SysCode": sys_core.SysCode;
    "SysCodeAction": sys_core.SysCodeAction;
    "SysCodeType": sys_core.SysCodeType;
    "SysDataObj": sys_core.SysDataObj;
    "SysDataObjAction": sys_core.SysDataObjAction;
    "SysDataObjActionGroup": sys_core.SysDataObjActionGroup;
    "SysDataObjColumn": sys_core.SysDataObjColumn;
    "SysDataObjColumnItemChange": sys_core.SysDataObjColumnItemChange;
    "SysDataObjColumnItemValue": sys_core.SysDataObjColumnItemValue;
    "SysDataObjColumnLink": sys_core.SysDataObjColumnLink;
    "SysDataObjFieldEmbedListConfig": sys_core.SysDataObjFieldEmbedListConfig;
    "SysDataObjFieldEmbedListEdit": sys_core.SysDataObjFieldEmbedListEdit;
    "SysDataObjFieldEmbedListSelect": sys_core.SysDataObjFieldEmbedListSelect;
    "SysDataObjFieldListItems": sys_core.SysDataObjFieldListItems;
    "SysDataObjFieldListItemsProp": sys_core.SysDataObjFieldListItemsProp;
    "SysDataObjQueryRider": sys_core.SysDataObjQueryRider;
    "SysDataObjTable": sys_core.SysDataObjTable;
    "SysDataObjWith": sys_core.SysDataObjWith;
    "SysMsg": sys_core.SysMsg;
    "SysNodeObj": sys_core.SysNodeObj;
    "SysNodeObjData": sys_core.SysNodeObjData;
    "SysNotify": sys_core.SysNotify;
    "SysObjEntAttr": sys_core.SysObjEntAttr;
    "SysObjNote": sys_core.SysObjNote;
    "SysOrg": sys_core.SysOrg;
    "SysSystem": sys_core.SysSystem;
  };
  "app_crm": {
    "CrmClient": app_crm.CrmClient;
  };
  "cfg": {
    "ConfigObject": cfg.ConfigObject;
    "AbstractConfig": cfg.AbstractConfig;
    "AllowBareDDL": cfg.AllowBareDDL;
    "Auth": cfg.Auth;
    "AuthMethod": cfg.AuthMethod;
    "DatabaseConfig": cfg.DatabaseConfig;
    "BranchConfig": cfg.BranchConfig;
    "Config": cfg.Config;
    "ConnectionTransport": cfg.ConnectionTransport;
    "ExtensionConfig": cfg.ExtensionConfig;
    "InstanceConfig": cfg.InstanceConfig;
    "JWT": cfg.JWT;
    "Password": cfg.Password;
    "QueryCacheMode": cfg.QueryCacheMode;
    "SCRAM": cfg.SCRAM;
    "Trust": cfg.Trust;
    "mTLS": cfg.mTLS;
  };
  "fts": {
    "ElasticLanguage": fts.ElasticLanguage;
    "Language": fts.Language;
    "LuceneLanguage": fts.LuceneLanguage;
    "PGLanguage": fts.PGLanguage;
    "Weight": fts.Weight;
  };
  "org_client_moed": {
    "MoedPartData": org_client_moed.MoedPartData;
    "MoedParticipant": org_client_moed.MoedParticipant;
  };
  "schema": {
    "AccessKind": schema.AccessKind;
    "Object": schema.$Object;
    "SubclassableObject": schema.SubclassableObject;
    "InheritingObject": schema.InheritingObject;
    "AnnotationSubject": schema.AnnotationSubject;
    "AccessPolicy": schema.AccessPolicy;
    "AccessPolicyAction": schema.AccessPolicyAction;
    "Alias": schema.Alias;
    "Annotation": schema.Annotation;
    "Type": schema.Type;
    "PrimitiveType": schema.PrimitiveType;
    "CollectionType": schema.CollectionType;
    "Array": schema.Array;
    "ArrayExprAlias": schema.ArrayExprAlias;
    "CallableObject": schema.CallableObject;
    "Cardinality": schema.Cardinality;
    "VolatilitySubject": schema.VolatilitySubject;
    "Cast": schema.Cast;
    "ConsistencySubject": schema.ConsistencySubject;
    "Constraint": schema.Constraint;
    "Delta": schema.Delta;
    "Extension": schema.Extension;
    "Function": schema.Function;
    "FutureBehavior": schema.FutureBehavior;
    "Global": schema.Global;
    "Index": schema.Index;
    "Pointer": schema.Pointer;
    "Source": schema.Source;
    "Link": schema.Link;
    "Migration": schema.Migration;
    "MigrationGeneratedBy": schema.MigrationGeneratedBy;
    "Module": schema.Module;
    "MultiRange": schema.MultiRange;
    "MultiRangeExprAlias": schema.MultiRangeExprAlias;
    "ObjectType": schema.ObjectType;
    "Operator": schema.Operator;
    "OperatorKind": schema.OperatorKind;
    "Parameter": schema.Parameter;
    "ParameterKind": schema.ParameterKind;
    "Property": schema.Property;
    "PseudoType": schema.PseudoType;
    "Range": schema.Range;
    "RangeExprAlias": schema.RangeExprAlias;
    "Rewrite": schema.Rewrite;
    "RewriteKind": schema.RewriteKind;
    "ScalarType": schema.ScalarType;
    "SourceDeleteAction": schema.SourceDeleteAction;
    "TargetDeleteAction": schema.TargetDeleteAction;
    "Trigger": schema.Trigger;
    "TriggerKind": schema.TriggerKind;
    "TriggerScope": schema.TriggerScope;
    "TriggerTiming": schema.TriggerTiming;
    "Tuple": schema.Tuple;
    "TupleElement": schema.TupleElement;
    "TupleExprAlias": schema.TupleExprAlias;
    "TypeModifier": schema.TypeModifier;
    "Volatility": schema.Volatility;
  };
  "sys": {
    "SystemObject": sys.SystemObject;
    "ExternalObject": sys.ExternalObject;
    "Database": sys.Database;
    "ExtensionPackage": sys.ExtensionPackage;
    "Role": sys.Role;
    "TransactionIsolation": sys.TransactionIsolation;
    "VersionStage": sys.VersionStage;
  };
  "sys_db": {
    "SysColumn": sys_db.SysColumn;
    "SysTable": sys_db.SysTable;
  };
  "sys_migr": {
    "SysMigr": sys_migr.SysMigr;
    "SysMigrSourceColumn": sys_migr.SysMigrSourceColumn;
    "SysMigrSourceTable": sys_migr.SysMigrSourceTable;
    "SysMigrTargetColumn": sys_migr.SysMigrTargetColumn;
    "SysMigrTargetTable": sys_migr.SysMigrTargetTable;
  };
  "sys_rep": {
    "SysAnalytic": sys_rep.SysAnalytic;
    "SysAnalyticStatus": sys_rep.SysAnalyticStatus;
    "SysRep": sys_rep.SysRep;
    "SysRepEl": sys_rep.SysRepEl;
    "SysRepParm": sys_rep.SysRepParm;
    "SysRepUser": sys_rep.SysRepUser;
    "SysRepUserAnalytic": sys_rep.SysRepUserAnalytic;
    "SysRepUserParm": sys_rep.SysRepUserParm;
  };
  "sys_test": {
    "Movie": sys_test.Movie;
    "Person": sys_test.Person;
  };
}


export namespace helper {
  type LinkType = std.BaseObject | std.BaseObject[];

  export type propertyKeys<T> = {
    [k in keyof T]: NonNullable<T[k]> extends LinkType ? never : k;
  }[keyof T];

  export type linkKeys<T> = {
    [k in keyof T]: NonNullable<T[k]> extends LinkType ? k : never;
  }[keyof T];

  export type Props<T> = Pick<T, propertyKeys<T>>;
  export type Links<T> = Pick<T, linkKeys<T>>;
}
